services:
  poke5e-db:
    image: supabase/postgres:17.0.1.007-orioledb
    restart: unless-stopped
    container_name: poke5e-db
    environment:
      POSTGRES_PASSWORD: postgres
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
