import path from "node:path"
import fs from "node:fs/promises"
import { superconsole } from "../superconsole.ts"
import { Report } from "./report.ts"

/**
 * Compares move-matrix.csv (generated by build-movesets.ts) against move-matrix-assigned.csv
 * (created independently, and used by assign-moves.ts to assign moves to the 2024 edition).
 *
 * The main goal is to ensure every level-up move in move-matrix.csv is in move-matrix-assigned.csv.
 * The assigned CSV only covers level-up moves, so egg and TM rows in move-matrix.csv are ignored.
 * A move counts as level-up if any game teaches it by level-up, or the 2018 edition of pokemon 5e does.
 *
 * As a sanity check, it also compares which moves each file says are already in pokemon 5e, and at what level.
 * - move-matrix.csv: "in p5e" and "p5e level" (1 means Start)
 * - move-matrix-assigned.csv: "Method" and "Poke5e Level" (0 means Start, -1 means not in pokemon 5e)
 *
 * Results are written to compare-move-matrices-report.md in the cache folder.
 */

const CACHE_FOLDER = path.join(import.meta.dirname, "cache")
const MATRIX_PATH = path.join(CACHE_FOLDER, "move-matrix.csv")
const ASSIGNED_PATH = path.join(CACHE_FOLDER, "move-matrix-assigned.csv")
const REPORT_PATH = path.join(CACHE_FOLDER, "compare-move-matrices-report.md")

const ALREADY = "In Poke 5e Already"

type MatrixRow = {
	pokemon: string,
	move: string,
	latestGame: string,
	latestLevel: string,
	p5eLevel: number | undefined, // 0 means Start
}

type AssignedRow = {
	pokemon: string,
	move: string,
	p5eLevel: number | undefined, // 0 means Start
	method: string,
}

const isLevel = (value: string) => /^\d+$/.test(value)
const levelName = (level: number) => level === 0 ? "Start" : `Lv ${level}`
const key = (pokemon: string, move: string) => `${pokemon}:${move}`

async function readCsv(file: string): Promise<{ col: (name: string) => number, lines: string[][] }> {
	const raw = await fs.readFile(file, { encoding: "utf-8" })
	const [header, ...lines] = raw.split(/\r?\n/).filter((line) => line.trim().length > 0)
	const columns = header.split(",")
	const col = (name: string) => {
		const i = columns.indexOf(name)
		if (i < 0) throw new Error(`Missing column in ${path.basename(file)}: ${name}`)
		return i
	}

	return { col, lines: lines.map((line) => line.split(",")) }
}

// Only level-up rows; a move learned by level-up and another method has a separate row per method
async function getMatrixRows(): Promise<MatrixRow[]> {
	const { col, lines } = await readCsv(MATRIX_PATH)
	const [pokemonCol, moveCol, latestGameCol, latestLevelCol, p5eLevelCol] = [col("pokemon id"), col("move id"), col("most recent game"), col("most recent level learned"), col("p5e level")]

	return lines
		.filter((cells) => isLevel(cells[latestLevelCol]) || isLevel(cells[p5eLevelCol]))
		.map((cells) => ({
			pokemon: cells[pokemonCol],
			move: cells[moveCol],
			latestGame: cells[latestGameCol],
			latestLevel: cells[latestLevelCol],
			p5eLevel: isLevel(cells[p5eLevelCol]) ? (Number(cells[p5eLevelCol]) === 1 ? 0 : Number(cells[p5eLevelCol])) : undefined,
		}))
}

async function getAssignedRows(): Promise<AssignedRow[]> {
	const { col, lines } = await readCsv(ASSIGNED_PATH)
	const [pokemonCol, moveCol, p5eLevelCol, methodCol] = [col("pokémon"), col("move"), col("Poke5e Level"), col("Method")]

	return lines.map((cells) => {
		const p5eLevel = Number(cells[p5eLevelCol])
		return {
			pokemon: cells[pokemonCol],
			move: cells[moveCol],
			p5eLevel: p5eLevel >= 0 ? p5eLevel : undefined,
			method: cells[methodCol].trim(),
		}
	})
}

const describeMatrix = (row: MatrixRow) => [
	row.latestGame !== "" ? `${row.latestGame} level ${row.latestLevel}` : "not in the games",
	row.p5eLevel != null ? `p5e ${levelName(row.p5eLevel)}` : "not in p5e",
].join("; ")

const SECTIONS = {
	missingPokemon: "Pokémon in move-matrix missing from move-matrix-assigned",
	missingMoves: "Level-up moves in move-matrix missing from move-matrix-assigned",
	duplicateAssigned: "Duplicate rows in move-matrix-assigned",
	extraMoves: "Moves in move-matrix-assigned that move-matrix does not list as level-up",
	alreadyNotInP5e: "Marked \"In Poke 5e Already\" but move-matrix says not in p5e",
	inP5eNotAlready: "In p5e per move-matrix but not marked \"In Poke 5e Already\"",
	p5eLevelMismatch: "Pokemon 5e level differs between the files",
}

async function main() {
	const [matrixRows, assignedRows] = await Promise.all([getMatrixRows(), getAssignedRows()])
	const report = new Report()

	const matrix = new Map(matrixRows.map((row) => [key(row.pokemon, row.move), row]))
	const assigned = new Map<string, AssignedRow>()
	for (const row of assignedRows) {
		const k = key(row.pokemon, row.move)
		if (assigned.has(k)) report.add(SECTIONS.duplicateAssigned, `${row.pokemon}: ${row.move}`)
		assigned.set(k, row)
	}

	const assignedPokemon = new Set(assignedRows.map((row) => row.pokemon))
	const missingPokemon = new Map<string, number>()

	for (const [k, row] of matrix) {
		if (!assignedPokemon.has(row.pokemon)) {
			missingPokemon.set(row.pokemon, (missingPokemon.get(row.pokemon) ?? 0) + 1)
			continue
		}

		const assignedRow = assigned.get(k)
		if (assignedRow == null) {
			report.add(SECTIONS.missingMoves, `${row.pokemon}: ${row.move} (${describeMatrix(row)})`)
			continue
		}

		const label = `${row.pokemon}: ${row.move}`
		const isAlready = assignedRow.method === ALREADY
		if (isAlready && row.p5eLevel == null) {
			report.add(SECTIONS.alreadyNotInP5e, `${label} (assigned says ${assignedRow.p5eLevel != null ? levelName(assignedRow.p5eLevel) : "no level"})`)
		} else if (!isAlready && row.p5eLevel != null) {
			report.add(SECTIONS.inP5eNotAlready, `${label} (p5e ${levelName(row.p5eLevel)}; assigned method is ${assignedRow.method})`)
		}

		if (row.p5eLevel != null && assignedRow.p5eLevel != null && row.p5eLevel !== assignedRow.p5eLevel) {
			report.add(SECTIONS.p5eLevelMismatch, `${label} (move-matrix says ${levelName(row.p5eLevel)}; assigned says ${levelName(assignedRow.p5eLevel)})`)
		}
	}

	for (const [pokemon, count] of missingPokemon) {
		report.add(SECTIONS.missingPokemon, `${pokemon} (${count} level-up moves)`)
	}

	for (const [k, row] of assigned) {
		if (!matrix.has(k)) {
			report.add(SECTIONS.extraMoves, `${row.pokemon}: ${row.move} (${row.method})`)
		}
	}

	const summary = [
		"# Compare Move Matrices Report",
		"",
		`Compared ${matrix.size} level-up moves in move-matrix.csv against ${assigned.size} moves in move-matrix-assigned.csv.`,
		"",
	].join("\n")
	await fs.writeFile(REPORT_PATH, `${summary}\n${report.toMarkdown(Object.values(SECTIONS))}`, { encoding: "utf-8" })

	const missing = report.count(SECTIONS.missingPokemon) + report.count(SECTIONS.missingMoves)
	if (missing === 0) {
		superconsole.success("Every level-up move in move-matrix.csv is in move-matrix-assigned.csv")
	} else {
		process.exitCode = 1
	}

	for (const section of Object.values(SECTIONS)) {
		const count = report.count(section)
		if (count > 0) superconsole.failure(`${section}: ${count}`)
	}
	superconsole.log(`Report written to ${REPORT_PATH}`)
}

main()
