INSERT INTO private.species_info
	(id, type)
VALUES
	('bulbasaur', ARRAY['grass', 'poison']),
	('ivysaur', ARRAY['grass', 'poison']),
	('venusaur', ARRAY['grass', 'poison']),
	('charmander', ARRAY['fire']),
	('charmeleon', ARRAY['fire']),
	('charizard', ARRAY['fire', 'flying']),
	('squirtle', ARRAY['water']),
	('wartortle', ARRAY['water']),
	('blastoise', ARRAY['water']),
	('caterpie', ARRAY['bug']),
	('metapod', ARRAY['bug']),
	('butterfree', ARRAY['bug', 'flying']),
	('weedle', ARRAY['bug', 'poison']),
	('kakuna', ARRAY['bug', 'poison']),
	('beedrill', ARRAY['bug', 'poison']),
	('pidgey', ARRAY['normal', 'flying']),
	('pidgeotto', ARRAY['normal', 'flying']),
	('pidgeot', ARRAY['normal', 'flying']),
	('rattata', ARRAY['normal']),
	('raticate', ARRAY['normal']),
	('spearow', ARRAY['normal', 'flying']),
	('fearow', ARRAY['normal', 'flying']),
	('ekans', ARRAY['poison']),
	('arbok', ARRAY['poison']),
	('pikachu', ARRAY['electric']),
	('raichu', ARRAY['electric']),
	('sandshrew', ARRAY['ground']),
	('sandslash', ARRAY['ground']),
	('nidoran-f', ARRAY['poison']),
	('nidorina', ARRAY['poison']),
	('nidoqueen', ARRAY['poison', 'ground']),
	('nidoran-m', ARRAY['poison']),
	('nidorino', ARRAY['poison']),
	('nidoking', ARRAY['poison', 'ground']),
	('clefairy', ARRAY['fairy']),
	('clefable', ARRAY['fairy']),
	('vulpix', ARRAY['fire']),
	('ninetales', ARRAY['fire']),
	('jigglypuff', ARRAY['normal', 'fairy']),
	('wigglytuff', ARRAY['normal', 'fairy']),
	('zubat', ARRAY['poison', 'flying']),
	('golbat', ARRAY['poison', 'flying']),
	('oddish', ARRAY['grass', 'poison']),
	('gloom', ARRAY['grass', 'poison']),
	('vileplume', ARRAY['grass', 'poison']),
	('paras', ARRAY['bug', 'grass']),
	('parasect', ARRAY['bug', 'grass']),
	('venonat', ARRAY['bug', 'poison']),
	('venomoth', ARRAY['bug', 'poison']),
	('diglett', ARRAY['ground']),
	('dugtrio', ARRAY['ground']),
	('meowth', ARRAY['normal']),
	('persian', ARRAY['normal']),
	('psyduck', ARRAY['water']),
	('golduck', ARRAY['water']),
	('mankey', ARRAY['fighting']),
	('primeape', ARRAY['fighting']),
	('growlithe', ARRAY['fire']),
	('arcanine', ARRAY['fire']),
	('poliwag', ARRAY['water']),
	('poliwhirl', ARRAY['water']),
	('poliwrath', ARRAY['water', 'fighting']),
	('abra', ARRAY['psychic']),
	('kadabra', ARRAY['psychic']),
	('alakazam', ARRAY['psychic']),
	('machop', ARRAY['fighting']),
	('machoke', ARRAY['fighting']),
	('machamp', ARRAY['fighting']),
	('bellsprout', ARRAY['grass', 'poison']),
	('weepinbell', ARRAY['grass', 'poison']),
	('victreebel', ARRAY['grass', 'poison']),
	('tentacool', ARRAY['water', 'poison']),
	('tentacruel', ARRAY['water', 'poison']),
	('geodude', ARRAY['rock', 'ground']),
	('graveler', ARRAY['rock', 'ground']),
	('golem', ARRAY['rock', 'ground']),
	('ponyta', ARRAY['fire']),
	('rapidash', ARRAY['fire']),
	('slowpoke', ARRAY['water', 'psychic']),
	('slowbro', ARRAY['water', 'psychic']),
	('magnemite', ARRAY['electric', 'steel']),
	('magneton', ARRAY['electric', 'steel']),
	('farfetchd', ARRAY['normal', 'flying']),
	('doduo', ARRAY['normal', 'flying']),
	('dodrio', ARRAY['normal', 'flying']),
	('seel', ARRAY['water']),
	('dewgong', ARRAY['water', 'ice']),
	('grimer', ARRAY['poison']),
	('muk', ARRAY['poison']),
	('shellder', ARRAY['water']),
	('cloyster', ARRAY['water', 'ice']),
	('gastly', ARRAY['ghost', 'poison']),
	('haunter', ARRAY['ghost', 'poison']),
	('gengar', ARRAY['ghost', 'poison']),
	('onix', ARRAY['rock', 'ground']),
	('drowzee', ARRAY['psychic']),
	('hypno', ARRAY['psychic']),
	('krabby', ARRAY['water']),
	('kingler', ARRAY['water']),
	('voltorb', ARRAY['electric']),
	('electrode', ARRAY['electric']),
	('exeggcute', ARRAY['grass', 'psychic']),
	('exeggutor', ARRAY['grass', 'psychic']),
	('cubone', ARRAY['ground']),
	('marowak', ARRAY['ground']),
	('hitmonlee', ARRAY['fighting']),
	('hitmonchan', ARRAY['fighting']),
	('lickitung', ARRAY['normal']),
	('koffing', ARRAY['poison']),
	('weezing', ARRAY['poison']),
	('rhyhorn', ARRAY['ground', 'rock']),
	('rhydon', ARRAY['ground', 'rock']),
	('chansey', ARRAY['normal']),
	('tangela', ARRAY['grass']),
	('kangaskhan', ARRAY['normal']),
	('horsea', ARRAY['water']),
	('seadra', ARRAY['water']),
	('goldeen', ARRAY['water']),
	('seaking', ARRAY['water']),
	('staryu', ARRAY['water']),
	('starmie', ARRAY['water', 'psychic']),
	('mr-mime', ARRAY['psychic', 'fairy']),
	('scyther', ARRAY['bug', 'flying']),
	('jynx', ARRAY['ice', 'psychic']),
	('electabuzz', ARRAY['electric']),
	('magmar', ARRAY['fire']),
	('pinsir', ARRAY['bug']),
	('tauros', ARRAY['normal']),
	('magikarp', ARRAY['water']),
	('gyarados', ARRAY['water', 'flying']),
	('lapras', ARRAY['water', 'ice']),
	('ditto', ARRAY['normal']),
	('eevee', ARRAY['normal']),
	('vaporeon', ARRAY['water']),
	('jolteon', ARRAY['electric']),
	('flareon', ARRAY['fire']),
	('porygon', ARRAY['normal']),
	('omanyte', ARRAY['rock', 'water']),
	('omastar', ARRAY['rock', 'water']),
	('kabuto', ARRAY['rock', 'water']),
	('kabutops', ARRAY['rock', 'water']),
	('aerodactyl', ARRAY['rock', 'flying']),
	('snorlax', ARRAY['normal']),
	('articuno', ARRAY['ice', 'flying']),
	('zapdos', ARRAY['electric', 'flying']),
	('moltres', ARRAY['fire', 'flying']),
	('dratini', ARRAY['dragon']),
	('dragonair', ARRAY['dragon']),
	('dragonite', ARRAY['dragon', 'flying']),
	('mewtwo', ARRAY['psychic']),
	('mew', ARRAY['psychic']),
	('chikorita', ARRAY['grass']),
	('bayleef', ARRAY['grass']),
	('meganium', ARRAY['grass']),
	('cyndaquil', ARRAY['fire']),
	('quilava', ARRAY['fire']),
	('typhlosion', ARRAY['fire']),
	('totodile', ARRAY['water']),
	('croconaw', ARRAY['water']),
	('feraligatr', ARRAY['water']),
	('sentret', ARRAY['normal']),
	('furret', ARRAY['normal']),
	('hoothoot', ARRAY['normal', 'flying']),
	('noctowl', ARRAY['normal', 'flying']),
	('ledyba', ARRAY['bug', 'flying']),
	('ledian', ARRAY['bug', 'flying']),
	('spinarak', ARRAY['bug', 'poison']),
	('ariados', ARRAY['bug', 'poison']),
	('crobat', ARRAY['poison', 'flying']),
	('chinchou', ARRAY['water', 'electric']),
	('lanturn', ARRAY['water', 'electric']),
	('pichu', ARRAY['electric']),
	('cleffa', ARRAY['fairy']),
	('igglybuff', ARRAY['normal', 'fairy']),
	('togepi', ARRAY['fairy']),
	('togetic', ARRAY['fairy', 'flying']),
	('natu', ARRAY['psychic', 'flying']),
	('xatu', ARRAY['psychic', 'flying']),
	('mareep', ARRAY['electric']),
	('flaaffy', ARRAY['electric']),
	('ampharos', ARRAY['electric']),
	('bellossom', ARRAY['grass']),
	('marill', ARRAY['water', 'fairy']),
	('azumarill', ARRAY['water', 'fairy']),
	('sudowoodo', ARRAY['rock']),
	('politoed', ARRAY['water']),
	('hoppip', ARRAY['grass', 'flying']),
	('skiploom', ARRAY['grass', 'flying']),
	('jumpluff', ARRAY['grass', 'flying']),
	('aipom', ARRAY['normal']),
	('sunkern', ARRAY['grass']),
	('sunflora', ARRAY['grass']),
	('yanma', ARRAY['bug', 'flying']),
	('wooper', ARRAY['water', 'ground']),
	('quagsire', ARRAY['water', 'ground']),
	('espeon', ARRAY['psychic']),
	('umbreon', ARRAY['dark']),
	('murkrow', ARRAY['dark', 'flying']),
	('slowking', ARRAY['water', 'psychic']),
	('misdreavus', ARRAY['ghost']),
	('unown', ARRAY['psychic']),
	('wobbuffet', ARRAY['psychic']),
	('girafarig', ARRAY['normal', 'psychic']),
	('pineco', ARRAY['bug']),
	('forretress', ARRAY['bug', 'steel']),
	('dunsparce', ARRAY['normal']),
	('gligar', ARRAY['ground', 'flying']),
	('steelix', ARRAY['steel', 'ground']),
	('snubbull', ARRAY['fairy']),
	('granbull', ARRAY['fairy']),
	('qwilfish', ARRAY['water', 'poison']),
	('scizor', ARRAY['bug', 'steel']),
	('shuckle', ARRAY['bug', 'rock']),
	('heracross', ARRAY['bug', 'fighting']),
	('sneasel', ARRAY['dark', 'ice']),
	('teddiursa', ARRAY['normal']),
	('ursaring', ARRAY['normal']),
	('slugma', ARRAY['fire']),
	('magcargo', ARRAY['fire', 'rock']),
	('swinub', ARRAY['ice', 'ground']),
	('piloswine', ARRAY['ice', 'ground']),
	('corsola', ARRAY['water', 'rock']),
	('remoraid', ARRAY['water']),
	('octillery', ARRAY['water']),
	('delibird', ARRAY['ice', 'flying']),
	('mantine', ARRAY['water', 'flying']),
	('skarmory', ARRAY['steel', 'flying']),
	('houndour', ARRAY['dark', 'fire']),
	('houndoom', ARRAY['dark', 'fire']),
	('kingdra', ARRAY['water', 'dragon']),
	('phanpy', ARRAY['ground']),
	('donphan', ARRAY['ground']),
	('porygon2', ARRAY['normal']),
	('stantler', ARRAY['normal']),
	('smeargle', ARRAY['normal']),
	('tyrogue', ARRAY['fighting']),
	('hitmontop', ARRAY['fighting']),
	('smoochum', ARRAY['ice', 'psychic']),
	('elekid', ARRAY['electric']),
	('magby', ARRAY['fire']),
	('miltank', ARRAY['normal']),
	('blissey', ARRAY['normal']),
	('raikou', ARRAY['electric']),
	('entei', ARRAY['fire']),
	('suicune', ARRAY['water']),
	('larvitar', ARRAY['rock', 'ground']),
	('pupitar', ARRAY['rock', 'ground']),
	('tyranitar', ARRAY['rock', 'dark']),
	('lugia', ARRAY['psychic', 'flying']),
	('ho-oh', ARRAY['fire', 'flying']),
	('celebi', ARRAY['grass', 'psychic']),
	('treecko', ARRAY['grass']),
	('grovyle', ARRAY['grass']),
	('sceptile', ARRAY['grass']),
	('torchic', ARRAY['fire']),
	('combusken', ARRAY['fire', 'fighting']),
	('blaziken', ARRAY['fire', 'fighting']),
	('mudkip', ARRAY['water']),
	('marshtomp', ARRAY['water', 'ground']),
	('swampert', ARRAY['water', 'ground']),
	('poochyena', ARRAY['dark']),
	('mightyena', ARRAY['dark']),
	('zigzagoon', ARRAY['normal']),
	('linoone', ARRAY['normal']),
	('wurmple', ARRAY['bug']),
	('silcoon', ARRAY['bug']),
	('beautifly', ARRAY['bug', 'flying']),
	('cascoon', ARRAY['bug']),
	('dustox', ARRAY['bug', 'poison']),
	('lotad', ARRAY['water', 'grass']),
	('lombre', ARRAY['water', 'grass']),
	('ludicolo', ARRAY['water', 'grass']),
	('seedot', ARRAY['grass']),
	('nuzleaf', ARRAY['grass', 'dark']),
	('shiftry', ARRAY['grass', 'dark']),
	('taillow', ARRAY['normal', 'flying']),
	('swellow', ARRAY['normal', 'flying']),
	('wingull', ARRAY['water', 'flying']),
	('pelipper', ARRAY['water', 'flying']),
	('ralts', ARRAY['psychic', 'fairy']),
	('kirlia', ARRAY['psychic', 'fairy']),
	('gardevoir', ARRAY['psychic', 'fairy']),
	('surskit', ARRAY['bug', 'water']),
	('masquerain', ARRAY['bug', 'flying']),
	('shroomish', ARRAY['grass']),
	('breloom', ARRAY['grass', 'fighting']),
	('slakoth', ARRAY['normal']),
	('vigoroth', ARRAY['normal']),
	('slaking', ARRAY['normal']),
	('nincada', ARRAY['bug', 'ground']),
	('ninjask', ARRAY['bug', 'flying']),
	('shedinja', ARRAY['bug', 'ghost']),
	('whismur', ARRAY['normal']),
	('loudred', ARRAY['normal']),
	('exploud', ARRAY['normal']),
	('makuhita', ARRAY['fighting']),
	('hariyama', ARRAY['fighting']),
	('azurill', ARRAY['normal', 'fairy']),
	('nosepass', ARRAY['rock']),
	('skitty', ARRAY['normal']),
	('delcatty', ARRAY['normal']),
	('sableye', ARRAY['dark', 'ghost']),
	('mawile', ARRAY['steel', 'fairy']),
	('aron', ARRAY['steel', 'rock']),
	('lairon', ARRAY['steel', 'rock']),
	('aggron', ARRAY['steel', 'rock']),
	('meditite', ARRAY['fighting', 'psychic']),
	('medicham', ARRAY['fighting', 'psychic']),
	('electrike', ARRAY['electric']),
	('manectric', ARRAY['electric']),
	('plusle', ARRAY['electric']),
	('minun', ARRAY['electric']),
	('volbeat', ARRAY['bug']),
	('illumise', ARRAY['bug']),
	('roselia', ARRAY['grass', 'poison']),
	('gulpin', ARRAY['poison']),
	('swalot', ARRAY['poison']),
	('carvanha', ARRAY['water', 'dark']),
	('sharpedo', ARRAY['water', 'dark']),
	('wailmer', ARRAY['water']),
	('wailord', ARRAY['water']),
	('numel', ARRAY['fire', 'ground']),
	('camerupt', ARRAY['fire', 'ground']),
	('torkoal', ARRAY['fire']),
	('spoink', ARRAY['psychic']),
	('grumpig', ARRAY['psychic']),
	('spinda', ARRAY['normal']),
	('trapinch', ARRAY['ground']),
	('vibrava', ARRAY['ground', 'dragon']),
	('flygon', ARRAY['ground', 'dragon']),
	('cacnea', ARRAY['grass']),
	('cacturne', ARRAY['grass', 'dark']),
	('swablu', ARRAY['normal', 'flying']),
	('altaria', ARRAY['dragon', 'flying']),
	('zangoose', ARRAY['normal']),
	('seviper', ARRAY['poison']),
	('lunatone', ARRAY['rock', 'psychic']),
	('solrock', ARRAY['rock', 'psychic']),
	('barboach', ARRAY['water', 'ground']),
	('whiscash', ARRAY['water', 'ground']),
	('corphish', ARRAY['water']),
	('crawdaunt', ARRAY['water', 'dark']),
	('baltoy', ARRAY['ground', 'psychic']),
	('claydol', ARRAY['ground', 'psychic']),
	('lileep', ARRAY['rock', 'grass']),
	('cradily', ARRAY['rock', 'grass']),
	('anorith', ARRAY['rock', 'bug']),
	('armaldo', ARRAY['rock', 'bug']),
	('feebas', ARRAY['water']),
	('milotic', ARRAY['water']),
	('castform', ARRAY['normal']),
	('sunny-castform', ARRAY['fire']),
	('rainy-castform', ARRAY['water']),
	('snowy-castform', ARRAY['ice']),
	('kecleon', ARRAY['normal']),
	('shuppet', ARRAY['ghost']),
	('banette', ARRAY['ghost']),
	('duskull', ARRAY['ghost']),
	('dusclops', ARRAY['ghost']),
	('tropius', ARRAY['grass', 'flying']),
	('chimecho', ARRAY['psychic']),
	('absol', ARRAY['dark']),
	('wynaut', ARRAY['psychic']),
	('snorunt', ARRAY['ice']),
	('glalie', ARRAY['ice']),
	('spheal', ARRAY['ice', 'water']),
	('sealeo', ARRAY['ice', 'water']),
	('walrein', ARRAY['ice', 'water']),
	('clamperl', ARRAY['water']),
	('huntail', ARRAY['water']),
	('gorebyss', ARRAY['water']),
	('relicanth', ARRAY['water', 'rock']),
	('luvdisc', ARRAY['water']),
	('bagon', ARRAY['dragon']),
	('shelgon', ARRAY['dragon']),
	('salamence', ARRAY['dragon', 'flying']),
	('beldum', ARRAY['steel', 'psychic']),
	('metang', ARRAY['steel', 'psychic']),
	('metagross', ARRAY['steel', 'psychic']),
	('regirock', ARRAY['rock']),
	('regice', ARRAY['ice']),
	('registeel', ARRAY['steel']),
	('latias', ARRAY['dragon', 'psychic']),
	('latios', ARRAY['dragon', 'psychic']),
	('kyogre', ARRAY['water']),
	('groudon', ARRAY['ground']),
	('rayquaza', ARRAY['dragon', 'flying']),
	('jirachi', ARRAY['steel', 'psychic']),
	('deoxys', ARRAY['psychic']),
	('turtwig', ARRAY['grass']),
	('grotle', ARRAY['grass']),
	('torterra', ARRAY['grass', 'ground']),
	('chimchar', ARRAY['fire']),
	('monferno', ARRAY['fire', 'fighting']),
	('infernape', ARRAY['fire', 'fighting']),
	('piplup', ARRAY['water']),
	('prinplup', ARRAY['water']),
	('empoleon', ARRAY['water', 'steel']),
	('starly', ARRAY['normal', 'flying']),
	('staravia', ARRAY['normal', 'flying']),
	('staraptor', ARRAY['normal', 'flying']),
	('bidoof', ARRAY['normal']),
	('bibarel', ARRAY['normal', 'water']),
	('kricketot', ARRAY['bug']),
	('kricketune', ARRAY['bug']),
	('shinx', ARRAY['electric']),
	('luxio', ARRAY['electric']),
	('luxray', ARRAY['electric']),
	('budew', ARRAY['grass', 'poison']),
	('roserade', ARRAY['grass', 'poison']),
	('cranidos', ARRAY['rock']),
	('rampardos', ARRAY['rock']),
	('shieldon', ARRAY['rock', 'steel']),
	('bastiodon', ARRAY['rock', 'steel']),
	('burmy', ARRAY['bug']),
	('wormadam-plant-cloak', ARRAY['bug', 'grass']),
	('wormadam-sand-cloak', ARRAY['bug', 'ground']),
	('wormadam-trash-cloak', ARRAY['bug', 'steel']),
	('mothim', ARRAY['bug', 'flying']),
	('combee', ARRAY['bug', 'flying']),
	('vespiquen', ARRAY['bug', 'flying']),
	('pachirisu', ARRAY['electric']),
	('buizel', ARRAY['water']),
	('floatzel', ARRAY['water']),
	('cherubi', ARRAY['grass']),
	('cherrim', ARRAY['grass']),
	('shellos', ARRAY['water']),
	('gastrodon', ARRAY['water', 'ground']),
	('ambipom', ARRAY['normal']),
	('drifloon', ARRAY['ghost', 'flying']),
	('drifblim', ARRAY['ghost', 'flying']),
	('buneary', ARRAY['normal']),
	('lopunny', ARRAY['normal']),
	('mismagius', ARRAY['ghost']),
	('honchkrow', ARRAY['dark', 'flying']),
	('glameow', ARRAY['normal']),
	('purugly', ARRAY['normal']),
	('chingling', ARRAY['psychic']),
	('stunky', ARRAY['poison', 'dark']),
	('skuntank', ARRAY['poison', 'dark']),
	('bronzor', ARRAY['steel', 'psychic']),
	('bronzong', ARRAY['steel', 'psychic']),
	('bonsly', ARRAY['rock']),
	('mime-jr', ARRAY['psychic', 'fairy']),
	('happiny', ARRAY['normal']),
	('chatot', ARRAY['normal', 'flying']),
	('spiritomb', ARRAY['ghost', 'dark']),
	('gible', ARRAY['dragon', 'ground']),
	('gabite', ARRAY['dragon', 'ground']),
	('garchomp', ARRAY['dragon', 'ground']),
	('munchlax', ARRAY['normal']),
	('riolu', ARRAY['fighting']),
	('lucario', ARRAY['fighting', 'steel']),
	('hippopotas', ARRAY['ground']),
	('hippowdon', ARRAY['ground']),
	('skorupi', ARRAY['poison', 'bug']),
	('drapion', ARRAY['poison', 'dark']),
	('croagunk', ARRAY['poison', 'fighting']),
	('toxicroak', ARRAY['poison', 'fighting']),
	('carnivine', ARRAY['grass']),
	('finneon', ARRAY['water']),
	('lumineon', ARRAY['water']),
	('mantyke', ARRAY['water', 'flying']),
	('snover', ARRAY['grass', 'ice']),
	('abomasnow', ARRAY['grass', 'ice']),
	('weavile', ARRAY['dark', 'ice']),
	('magnezone', ARRAY['electric', 'steel']),
	('lickilicky', ARRAY['normal']),
	('rhyperior', ARRAY['ground', 'rock']),
	('tangrowth', ARRAY['grass']),
	('electivire', ARRAY['electric']),
	('magmortar', ARRAY['fire']),
	('togekiss', ARRAY['fairy', 'flying']),
	('yanmega', ARRAY['bug', 'flying']),
	('leafeon', ARRAY['grass']),
	('glaceon', ARRAY['ice']),
	('gliscor', ARRAY['ground', 'flying']),
	('mamoswine', ARRAY['ice', 'ground']),
	('porygon-z', ARRAY['normal']),
	('gallade', ARRAY['psychic', 'fighting']),
	('probopass', ARRAY['rock', 'steel']),
	('dusknoir', ARRAY['ghost']),
	('froslass', ARRAY['ice', 'ghost']),
	('rotom', ARRAY['electric', 'ghost']),
	('rotom-heat', ARRAY['electric', 'fire']),
	('rotom-wash', ARRAY['electric', 'water']),
	('rotom-frost', ARRAY['electric', 'ice']),
	('rotom-fan', ARRAY['electric', 'flying']),
	('rotom-mow', ARRAY['electric', 'grass']),
	('uxie', ARRAY['psychic']),
	('mesprit', ARRAY['psychic']),
	('azelf', ARRAY['psychic']),
	('dialga', ARRAY['steel', 'dragon']),
	('dialga-origin', ARRAY['steel', 'dragon']),
	('palkia', ARRAY['water', 'dragon']),
	('palkia-origin', ARRAY['water', 'dragon']),
	('heatran', ARRAY['fire', 'steel']),
	('regigigas', ARRAY['normal']),
	('giratina-altered-forme', ARRAY['ghost', 'dragon']),
	('giratina-origin-forme', ARRAY['ghost', 'dragon']),
	('cresselia', ARRAY['psychic']),
	('phione', ARRAY['water']),
	('manaphy', ARRAY['water']),
	('darkrai', ARRAY['dark']),
	('shaymin-land', ARRAY['grass']),
	('shaymin-sky', ARRAY['grass', 'flying']),
	('arceus', ARRAY['normal']),
	('victini', ARRAY['psychic', 'fire']),
	('snivy', ARRAY['grass']),
	('servine', ARRAY['grass']),
	('serperior', ARRAY['grass']),
	('tepig', ARRAY['fire']),
	('pignite', ARRAY['fire', 'fighting']),
	('emboar', ARRAY['fire', 'fighting']),
	('oshawott', ARRAY['water']),
	('dewott', ARRAY['water']),
	('samurott', ARRAY['water']),
	('patrat', ARRAY['normal']),
	('watchog', ARRAY['normal']),
	('lillipup', ARRAY['normal']),
	('herdier', ARRAY['normal']),
	('stoutland', ARRAY['normal']),
	('purrloin', ARRAY['dark']),
	('liepard', ARRAY['dark']),
	('pansage', ARRAY['grass']),
	('simisage', ARRAY['grass']),
	('pansear', ARRAY['fire']),
	('simisear', ARRAY['fire']),
	('panpour', ARRAY['water']),
	('simipour', ARRAY['water']),
	('munna', ARRAY['psychic']),
	('musharna', ARRAY['psychic']),
	('pidove', ARRAY['normal', 'flying']),
	('tranquill', ARRAY['normal', 'flying']),
	('unfezant', ARRAY['normal', 'flying']),
	('blitzle', ARRAY['electric']),
	('zebstrika', ARRAY['electric']),
	('roggenrola', ARRAY['rock']),
	('boldore', ARRAY['rock']),
	('gigalith', ARRAY['rock']),
	('woobat', ARRAY['psychic', 'flying']),
	('swoobat', ARRAY['psychic', 'flying']),
	('drilbur', ARRAY['ground']),
	('excadrill', ARRAY['steel', 'ground']),
	('audino', ARRAY['normal']),
	('timburr', ARRAY['fighting']),
	('gurdurr', ARRAY['fighting']),
	('conkeldurr', ARRAY['fighting']),
	('tympole', ARRAY['water']),
	('palpitoad', ARRAY['water', 'ground']),
	('seismitoad', ARRAY['water', 'ground']),
	('throh', ARRAY['fighting']),
	('sawk', ARRAY['fighting']),
	('sewaddle', ARRAY['bug', 'grass']),
	('swadloon', ARRAY['bug', 'grass']),
	('leavanny', ARRAY['bug', 'grass']),
	('venipede', ARRAY['bug', 'poison']),
	('whirlipede', ARRAY['bug', 'poison']),
	('scolipede', ARRAY['bug', 'poison']),
	('cottonee', ARRAY['grass', 'fairy']),
	('whimsicott', ARRAY['grass', 'fairy']),
	('petilil', ARRAY['grass']),
	('lilligant', ARRAY['grass']),
	('basculin', ARRAY['water']),
	('sandile', ARRAY['ground', 'dark']),
	('krokorok', ARRAY['ground', 'dark']),
	('krookodile', ARRAY['ground', 'dark']),
	('darumaka', ARRAY['fire']),
	('darmanitan', ARRAY['fire']),
	('maractus', ARRAY['grass']),
	('dwebble', ARRAY['bug', 'rock']),
	('crustle', ARRAY['bug', 'rock']),
	('scraggy', ARRAY['dark', 'fighting']),
	('scrafty', ARRAY['dark', 'fighting']),
	('sigilyph', ARRAY['psychic', 'flying']),
	('yamask', ARRAY['ghost']),
	('cofagrigus', ARRAY['ghost']),
	('tirtouga', ARRAY['water', 'rock']),
	('carracosta', ARRAY['water', 'rock']),
	('archen', ARRAY['rock', 'flying']),
	('archeops', ARRAY['rock', 'flying']),
	('trubbish', ARRAY['poison']),
	('garbodor', ARRAY['poison']),
	('zorua', ARRAY['dark']),
	('zoroark', ARRAY['dark']),
	('minccino', ARRAY['normal']),
	('cinccino', ARRAY['normal']),
	('gothita', ARRAY['psychic']),
	('gothorita', ARRAY['psychic']),
	('gothitelle', ARRAY['psychic']),
	('solosis', ARRAY['psychic']),
	('duosion', ARRAY['psychic']),
	('reuniclus', ARRAY['psychic']),
	('ducklett', ARRAY['water', 'flying']),
	('swanna', ARRAY['water', 'flying']),
	('vanillite', ARRAY['ice']),
	('vanillish', ARRAY['ice']),
	('vanilluxe', ARRAY['ice']),
	('deerling', ARRAY['normal', 'grass']),
	('sawsbuck', ARRAY['normal', 'grass']),
	('emolga', ARRAY['electric', 'flying']),
	('karrablast', ARRAY['bug']),
	('escavalier', ARRAY['bug', 'steel']),
	('foongus', ARRAY['grass', 'poison']),
	('amoonguss', ARRAY['grass', 'poison']),
	('frillish', ARRAY['water', 'ghost']),
	('jellicent', ARRAY['water', 'ghost']),
	('alomomola', ARRAY['water']),
	('joltik', ARRAY['bug', 'electric']),
	('galvantula', ARRAY['bug', 'electric']),
	('ferroseed', ARRAY['grass', 'steel']),
	('ferrothorn', ARRAY['grass', 'steel']),
	('klink', ARRAY['steel']),
	('klang', ARRAY['steel']),
	('klinklang', ARRAY['steel']),
	('tynamo', ARRAY['electric']),
	('eelektrik', ARRAY['electric']),
	('eelektross', ARRAY['electric']),
	('elgyem', ARRAY['psychic']),
	('beheeyem', ARRAY['psychic']),
	('litwick', ARRAY['ghost', 'fire']),
	('lampent', ARRAY['ghost', 'fire']),
	('chandelure', ARRAY['ghost', 'fire']),
	('axew', ARRAY['dragon']),
	('fraxure', ARRAY['dragon']),
	('haxorus', ARRAY['dragon']),
	('cubchoo', ARRAY['ice']),
	('beartic', ARRAY['ice']),
	('cryogonal', ARRAY['ice']),
	('shelmet', ARRAY['bug']),
	('accelgor', ARRAY['bug']),
	('stunfisk', ARRAY['ground', 'electric']),
	('mienfoo', ARRAY['fighting']),
	('mienshao', ARRAY['fighting']),
	('druddigon', ARRAY['dragon']),
	('golett', ARRAY['ground', 'ghost']),
	('golurk', ARRAY['ground', 'ghost']),
	('pawniard', ARRAY['dark', 'steel']),
	('bisharp', ARRAY['dark', 'steel']),
	('bouffalant', ARRAY['normal']),
	('rufflet', ARRAY['normal', 'flying']),
	('braviary', ARRAY['normal', 'flying']),
	('vullaby', ARRAY['dark', 'flying']),
	('mandibuzz', ARRAY['dark', 'flying']),
	('heatmor', ARRAY['fire']),
	('durant', ARRAY['bug', 'steel']),
	('deino', ARRAY['dark', 'dragon']),
	('zweilous', ARRAY['dark', 'dragon']),
	('hydreigon', ARRAY['dark', 'dragon']),
	('larvesta', ARRAY['bug', 'fire']),
	('volcarona', ARRAY['bug', 'fire']),
	('cobalion', ARRAY['steel', 'fighting']),
	('terrakion', ARRAY['rock', 'fighting']),
	('virizion', ARRAY['grass', 'fighting']),
	('tornadus', ARRAY['flying']),
	('thundurus', ARRAY['electric', 'flying']),
	('reshiram', ARRAY['dragon', 'fire']),
	('zekrom', ARRAY['dragon', 'electric']),
	('landorus', ARRAY['ground', 'flying']),
	('kyurem', ARRAY['dragon', 'ice']),
	('white-kyurem', ARRAY['dragon', 'ice']),
	('black-kyurem', ARRAY['dragon', 'ice']),
	('keldeo', ARRAY['water', 'fighting']),
	('meloetta---aria', ARRAY['normal', 'psychic']),
	('meloetta---pirouette', ARRAY['normal', 'fighting']),
	('genesect', ARRAY['bug', 'steel']),
	('chespin', ARRAY['grass']),
	('quilladin', ARRAY['grass']),
	('chesnaught', ARRAY['grass', 'fighting']),
	('fennekin', ARRAY['fire']),
	('braixen', ARRAY['fire']),
	('delphox', ARRAY['fire', 'psychic']),
	('froakie', ARRAY['water']),
	('frogadier', ARRAY['water']),
	('greninja', ARRAY['water', 'dark']),
	('bunnelby', ARRAY['normal']),
	('diggersby', ARRAY['normal', 'ground']),
	('fletchling', ARRAY['normal', 'flying']),
	('fletchinder', ARRAY['fire', 'flying']),
	('talonflame', ARRAY['fire', 'flying']),
	('scatterbug', ARRAY['bug']),
	('spewpa', ARRAY['bug']),
	('vivillon', ARRAY['bug', 'flying']),
	('litleo', ARRAY['fire', 'normal']),
	('pyroar', ARRAY['fire', 'normal']),
	('flabebe', ARRAY['fairy']),
	('floette', ARRAY['fairy']),
	('florges', ARRAY['fairy']),
	('skiddo', ARRAY['grass']),
	('gogoat', ARRAY['grass']),
	('pancham', ARRAY['fighting']),
	('pangoro', ARRAY['fighting', 'dark']),
	('furfrou', ARRAY['normal']),
	('espurr', ARRAY['psychic']),
	('meowstic-m', ARRAY['psychic']),
	('meowstic-f', ARRAY['psychic']),
	('honedge', ARRAY['steel', 'ghost']),
	('doublade', ARRAY['steel', 'ghost']),
	('aegislash', ARRAY['steel', 'ghost']),
	('spritzee', ARRAY['fairy']),
	('aromatisse', ARRAY['fairy']),
	('swirlix', ARRAY['fairy']),
	('slurpuff', ARRAY['fairy']),
	('inkay', ARRAY['dark', 'psychic']),
	('malamar', ARRAY['dark', 'psychic']),
	('binacle', ARRAY['rock', 'water']),
	('barbaracle', ARRAY['rock', 'water']),
	('skrelp', ARRAY['poison', 'water']),
	('dragalge', ARRAY['poison', 'dragon']),
	('clauncher', ARRAY['water']),
	('clawitzer', ARRAY['water']),
	('helioptile', ARRAY['electric', 'normal']),
	('heliolisk', ARRAY['electric', 'normal']),
	('tyrunt', ARRAY['rock', 'dragon']),
	('tyrantrum', ARRAY['rock', 'dragon']),
	('amaura', ARRAY['rock', 'ice']),
	('aurorus', ARRAY['rock', 'ice']),
	('sylveon', ARRAY['fairy']),
	('hawlucha', ARRAY['fighting', 'flying']),
	('dedenne', ARRAY['electric', 'fairy']),
	('carbink', ARRAY['rock', 'fairy']),
	('goomy', ARRAY['dragon']),
	('sliggoo', ARRAY['dragon']),
	('goodra', ARRAY['dragon']),
	('klefki', ARRAY['steel', 'fairy']),
	('phantump', ARRAY['ghost', 'grass']),
	('trevenant', ARRAY['ghost', 'grass']),
	('pumpkaboo', ARRAY['ghost', 'grass']),
	('gourgeist', ARRAY['ghost', 'grass']),
	('bergmite', ARRAY['ice']),
	('avalugg', ARRAY['ice']),
	('noibat', ARRAY['flying', 'dragon']),
	('noivern', ARRAY['flying', 'dragon']),
	('xerneas', ARRAY['fairy']),
	('yveltal', ARRAY['dark', 'flying']),
	('zygarde-10-forme', ARRAY['dragon', 'ground']),
	('zygarde-50-forme', ARRAY['dragon', 'ground']),
	('zygarde-complete-forme', ARRAY['dragon', 'ground']),
	('diancie', ARRAY['rock', 'fairy']),
	('hoopa-confined', ARRAY['psychic', 'ghost']),
	('hoopa-unbound', ARRAY['psychic', 'dark']),
	('volcanion', ARRAY['fire', 'water']),
	('alolan-rattata', ARRAY['dark', 'normal']),
	('alolan-raticate', ARRAY['dark', 'normal']),
	('alolan-raichu', ARRAY['electric', 'psychic']),
	('alolan-sandshrew', ARRAY['ice', 'steel']),
	('alolan-sandslash', ARRAY['ice', 'steel']),
	('alolan-vulpix', ARRAY['ice']),
	('alolan-ninetales', ARRAY['ice', 'fairy']),
	('alolan-diglett', ARRAY['ground', 'steel']),
	('alolan-dugtrio', ARRAY['ground', 'steel']),
	('alolan-meowth', ARRAY['dark']),
	('alolan-persian', ARRAY['dark']),
	('alolan-geodude', ARRAY['rock', 'electric']),
	('alolan-graveler', ARRAY['rock', 'electric']),
	('alolan-golem', ARRAY['rock', 'electric']),
	('alolan-grimer', ARRAY['poison', 'dark']),
	('alolan-muk', ARRAY['poison', 'dark']),
	('alolan-exeggutor', ARRAY['grass', 'dragon']),
	('alolan-marowak', ARRAY['fire', 'ghost']),
	('rowlet', ARRAY['grass', 'flying']),
	('dartrix', ARRAY['grass', 'flying']),
	('decidueye', ARRAY['grass', 'ghost']),
	('litten', ARRAY['fire']),
	('torracat', ARRAY['fire']),
	('incineroar', ARRAY['fire', 'dark']),
	('popplio', ARRAY['water']),
	('brionne', ARRAY['water']),
	('primarina', ARRAY['water', 'fairy']),
	('pikipek', ARRAY['normal', 'flying']),
	('trumbeak', ARRAY['normal', 'flying']),
	('toucannon', ARRAY['normal', 'flying']),
	('yungoos', ARRAY['normal']),
	('gumshoos', ARRAY['normal']),
	('grubbin', ARRAY['bug']),
	('charjabug', ARRAY['bug', 'electric']),
	('vikavolt', ARRAY['bug', 'electric']),
	('crabrawler', ARRAY['fighting']),
	('crabominable', ARRAY['fighting', 'ice']),
	('oricorio-baile-style', ARRAY['fire', 'flying']),
	('oricorio-pom-pom-style', ARRAY['electric', 'flying']),
	('oricorio-pau-style', ARRAY['psychic', 'flying']),
	('oricorio-sensu-style', ARRAY['ghost', 'flying']),
	('cutiefly', ARRAY['bug', 'fairy']),
	('ribombee', ARRAY['bug', 'fairy']),
	('rockruff', ARRAY['rock']),
	('lycanroc-midday-form', ARRAY['rock']),
	('lycanroc-midnight-form', ARRAY['rock']),
	('lycanroc-dusk-form', ARRAY['rock']),
	('wishiwashi-solo-form', ARRAY['water']),
	('wishiwashi-school-form', ARRAY['water']),
	('mareanie', ARRAY['poison', 'water']),
	('toxapex', ARRAY['poison', 'water']),
	('mudbray', ARRAY['ground']),
	('mudsdale', ARRAY['ground']),
	('dewpider', ARRAY['water', 'bug']),
	('araquanid', ARRAY['water', 'bug']),
	('fomantis', ARRAY['grass']),
	('lurantis', ARRAY['grass']),
	('morelull', ARRAY['grass', 'fairy']),
	('shiinotic', ARRAY['grass', 'fairy']),
	('salandit', ARRAY['poison', 'fire']),
	('salazzle', ARRAY['poison', 'fire']),
	('stufful', ARRAY['normal', 'fighting']),
	('bewear', ARRAY['normal', 'fighting']),
	('bounsweet', ARRAY['grass']),
	('steenee', ARRAY['grass']),
	('tsareena', ARRAY['grass']),
	('comfey', ARRAY['fairy']),
	('oranguru', ARRAY['normal', 'psychic']),
	('passimian', ARRAY['fighting']),
	('wimpod', ARRAY['bug', 'water']),
	('golisopod', ARRAY['bug', 'water']),
	('sandygast', ARRAY['ghost', 'ground']),
	('palossand', ARRAY['ghost', 'ground']),
	('pyukumuku', ARRAY['water']),
	('type-null', ARRAY['normal']),
	('silvally', ARRAY['normal']),
	('minior-meteor-form', ARRAY['rock', 'flying']),
	('minior-core-form', ARRAY['rock', 'flying']),
	('komala', ARRAY['normal']),
	('turtonator', ARRAY['fire', 'dragon']),
	('togedemaru', ARRAY['electric', 'steel']),
	('mimikyu', ARRAY['ghost', 'fairy']),
	('bruxish', ARRAY['water', 'psychic']),
	('drampa', ARRAY['normal', 'dragon']),
	('dhelmise', ARRAY['ghost', 'grass']),
	('jangmo-o', ARRAY['dragon']),
	('hakamo-o', ARRAY['dragon', 'fighting']),
	('kommo-o', ARRAY['dragon', 'fighting']),
	('tapu-koko', ARRAY['electric', 'fairy']),
	('tapu-lele', ARRAY['psychic', 'fairy']),
	('tapu-bulu', ARRAY['grass', 'fairy']),
	('tapu-fini', ARRAY['water', 'fairy']),
	('cosmog', ARRAY['psychic']),
	('cosmoem', ARRAY['psychic']),
	('solgaleo', ARRAY['psychic', 'steel']),
	('lunala', ARRAY['psychic', 'ghost']),
	('nihilego', ARRAY['rock', 'poison']),
	('buzzwole', ARRAY['bug', 'fighting']),
	('pheromosa', ARRAY['bug', 'fighting']),
	('xurkitree', ARRAY['electric']),
	('celesteela', ARRAY['steel', 'flying']),
	('kartana', ARRAY['grass', 'steel']),
	('guzzlord', ARRAY['dark', 'dragon']),
	('necrozma', ARRAY['psychic']),
	('dusk-mane-necrozma', ARRAY['psychic', 'steel']),
	('dawn-wings-necrozma', ARRAY['psychic', 'ghost']),
	('ultra-necrozma', ARRAY['psychic', 'dragon']),
	('magearna', ARRAY['steel', 'fairy']),
	('marshadow', ARRAY['fighting', 'ghost']),
	('poipole', ARRAY['poison']),
	('naganadel', ARRAY['poison', 'dragon']),
	('stakataka', ARRAY['rock', 'steel']),
	('blacephalon', ARRAY['fire', 'ghost']),
	('zeraora', ARRAY['electric']),
	('meltan', ARRAY['steel']),
	('melmetal', ARRAY['steel']),
	('galarian-meowth', ARRAY['steel']),
	('galarian-ponyta', ARRAY['psychic']),
	('galarian-rapidash', ARRAY['psychic', 'fairy']),
	('galarian-slowpoke', ARRAY['psychic']),
	('galarian-slowbro', ARRAY['poison', 'psychic']),
	('galarian-farfetchd', ARRAY['fighting']),
	('galarian-weezing', ARRAY['poison', 'fairy']),
	('galarian-mr-mime', ARRAY['ice', 'psychic']),
	('articuno-galar', ARRAY['psychic', 'flying']),
	('zapdos-galar', ARRAY['fighting', 'flying']),
	('moltres-galar', ARRAY['dark', 'flying']),
	('galarian-slowking', ARRAY['poison', 'psychic']),
	('galarian-corsola', ARRAY['ghost']),
	('galarian-zigzagoon', ARRAY['dark', 'normal']),
	('galarian-linoone', ARRAY['dark', 'normal']),
	('galarian-darumaka', ARRAY['ice']),
	('galarian-darmanitan', ARRAY['ice']),
	('galarian-yamask', ARRAY['ground', 'ghost']),
	('galarian-stunfisk', ARRAY['ground', 'steel']),
	('grookey', ARRAY['grass']),
	('thwackey', ARRAY['grass']),
	('rillaboom', ARRAY['grass']),
	('scorbunny', ARRAY['fire']),
	('raboot', ARRAY['fire']),
	('cinderace', ARRAY['fire']),
	('sobble', ARRAY['water']),
	('drizzile', ARRAY['water']),
	('inteleon', ARRAY['water']),
	('skwovet', ARRAY['normal']),
	('greedent', ARRAY['normal']),
	('rookidee', ARRAY['flying']),
	('corvisquire', ARRAY['flying']),
	('corviknight', ARRAY['flying', 'steel']),
	('blipbug', ARRAY['bug']),
	('dottler', ARRAY['bug', 'psychic']),
	('orbeetle', ARRAY['bug', 'psychic']),
	('nickit', ARRAY['dark']),
	('thievul', ARRAY['dark']),
	('gossifleur', ARRAY['grass']),
	('eldegoss', ARRAY['grass']),
	('wooloo', ARRAY['normal']),
	('dubwool', ARRAY['normal']),
	('chewtle', ARRAY['water']),
	('drednaw', ARRAY['water', 'rock']),
	('yamper', ARRAY['electric']),
	('boltund', ARRAY['electric']),
	('rolycoly', ARRAY['rock']),
	('carkol', ARRAY['rock', 'fire']),
	('coalossal', ARRAY['rock', 'fire']),
	('applin', ARRAY['grass', 'dragon']),
	('flapple', ARRAY['grass', 'dragon']),
	('appletun', ARRAY['grass', 'dragon']),
	('silicobra', ARRAY['ground']),
	('sandaconda', ARRAY['ground']),
	('cramorant', ARRAY['flying', 'water']),
	('arrokuda', ARRAY['water']),
	('barraskewda', ARRAY['water']),
	('toxel', ARRAY['electric', 'poison']),
	('toxtricity-amped', ARRAY['electric', 'poison']),
	('toxtricity-low-key', ARRAY['electric', 'poison']),
	('sizzlipede', ARRAY['fire', 'bug']),
	('centiskorch', ARRAY['fire', 'bug']),
	('clobbopus', ARRAY['fighting']),
	('grapploct', ARRAY['fighting']),
	('sinistea', ARRAY['ghost']),
	('polteageist', ARRAY['ghost']),
	('hatenna', ARRAY['psychic']),
	('hattrem', ARRAY['psychic']),
	('hatterene', ARRAY['psychic', 'fairy']),
	('impidimp', ARRAY['dark', 'fairy']),
	('morgrem', ARRAY['dark', 'fairy']),
	('grimmsnarl', ARRAY['dark', 'fairy']),
	('obstagoon', ARRAY['dark', 'normal']),
	('perrserker', ARRAY['steel']),
	('cursola', ARRAY['ghost']),
	('sirfetchd', ARRAY['fighting']),
	('mr-rime', ARRAY['ice', 'psychic']),
	('runerigus', ARRAY['ground', 'ghost']),
	('milcery', ARRAY['fairy']),
	('alcremie', ARRAY['fairy']),
	('falinks', ARRAY['fighting']),
	('pincurchin', ARRAY['electric']),
	('snom', ARRAY['ice', 'bug']),
	('frosmoth', ARRAY['ice', 'bug']),
	('stonjourner', ARRAY['rock']),
	('eiscue', ARRAY['ice']),
	('indeedee-m', ARRAY['psychic', 'normal']),
	('indeedee-f', ARRAY['psychic', 'normal']),
	('morpeko', ARRAY['electric', 'dark']),
	('cufant', ARRAY['steel']),
	('copperajah', ARRAY['steel']),
	('dracozolt', ARRAY['electric', 'dragon']),
	('arctozolt', ARRAY['electric', 'ice']),
	('dracovish', ARRAY['water', 'dragon']),
	('arctovish', ARRAY['water', 'ice']),
	('duraludon', ARRAY['steel', 'dragon']),
	('dreepy', ARRAY['dragon', 'ghost']),
	('drakloak', ARRAY['dragon', 'ghost']),
	('dragapult', ARRAY['dragon', 'ghost']),
	('zacian', ARRAY['fairy']),
	('zacian-crowned', ARRAY['fairy', 'steel']),
	('zamazenta', ARRAY['fighting']),
	('zamazenta-crowned', ARRAY['fighting', 'steel']),
	('eternatus', ARRAY['poison', 'dragon']),
	('eternatus-eternamax', ARRAY['poison', 'dragon']),
	('kubfu', ARRAY['fighting']),
	('urshifu-single', ARRAY['fighting', 'dark']),
	('urshifu-rapid', ARRAY['fighting', 'water']),
	('zarude', ARRAY['dark', 'grass']),
	('regieleki', ARRAY['electric']),
	('regidrago', ARRAY['dragon']),
	('glastrier', ARRAY['ice']),
	('spectrier', ARRAY['ghost']),
	('calyrex', ARRAY['psychic', 'grass']),
	('calyrex-ice', ARRAY['psychic', 'ice']),
	('calyrex-shadow', ARRAY['psychic', 'ghost']),
	('growlithe-hisui', ARRAY['fire', 'rock']),
	('arcanine-hisui', ARRAY['fire', 'rock']),
	('voltorb-hisui', ARRAY['electric', 'grass']),
	('electrode-hisui', ARRAY['electric', 'grass']),
	('typhlosion-hisui', ARRAY['fire', 'ghost']),
	('qwilfish-hisui', ARRAY['dark', 'poison']),
	('sneasel-hisui', ARRAY['fighting', 'poison']),
	('samurott-hisui', ARRAY['water', 'dark']),
	('lilligant-hisui', ARRAY['grass', 'fighting']),
	('zorua-hisui', ARRAY['normal', 'ghost']),
	('zoroark-hisui', ARRAY['normal', 'ghost']),
	('braviary-hisui', ARRAY['psychic', 'flying']),
	('sliggoo-hisui', ARRAY['steel', 'dragon']),
	('goodra-hisui', ARRAY['steel', 'dragon']),
	('avalugg-hisui', ARRAY['ice', 'rock']),
	('decidueye-hisui', ARRAY['grass', 'fighting']),
	('wyrdeer', ARRAY['normal', 'psychic']),
	('kleavor', ARRAY['bug', 'rock']),
	('ursaluna', ARRAY['ground', 'normal']),
	('ursaluna-bloodmoon', ARRAY['ground', 'normal']),
	('basculegion-m', ARRAY['water', 'ghost']),
	('basculegion-f', ARRAY['water', 'ghost']),
	('sneasler', ARRAY['fighting', 'poison']),
	('overqwil', ARRAY['dark', 'poison']),
	('enamorus', ARRAY['fairy', 'flying']),
	('tauros-paldea-combat-breed', ARRAY['fighting']),
	('tauros-paldea-blaze-breed', ARRAY['fighting', 'fire']),
	('tauros-paldea-aqua-breed', ARRAY['fighting', 'water']),
	('wooper-paldea', ARRAY['poison', 'ground']),
	('sprigatito', ARRAY['grass']),
	('floragato', ARRAY['grass']),
	('meowscarada', ARRAY['grass', 'dark']),
	('fuecoco', ARRAY['fire']),
	('crocalor', ARRAY['fire']),
	('skeledirge', ARRAY['fire', 'ghost']),
	('quaxly', ARRAY['water']),
	('quaxwell', ARRAY['water']),
	('quaquaval', ARRAY['water', 'fighting']),
	('lechonk', ARRAY['normal']),
	('oinkologne-male', ARRAY['normal']),
	('oinkologne-female', ARRAY['normal']),
	('tarountula', ARRAY['bug']),
	('spidops', ARRAY['bug']),
	('nymble', ARRAY['bug']),
	('lokix', ARRAY['bug', 'dark']),
	('pawmi', ARRAY['electric']),
	('pawmo', ARRAY['electric', 'fighting']),
	('pawmot', ARRAY['electric', 'fighting']),
	('tandemaus', ARRAY['normal']),
	('maushold', ARRAY['normal']),
	('fidough', ARRAY['fairy']),
	('dachsbun', ARRAY['fairy']),
	('smoliv', ARRAY['grass', 'normal']),
	('dolliv', ARRAY['grass', 'normal']),
	('arboliva', ARRAY['grass', 'normal']),
	('squawkabilly', ARRAY['normal', 'flying']),
	('nacli', ARRAY['rock']),
	('naclstack', ARRAY['rock']),
	('garganacl', ARRAY['rock']),
	('charcadet', ARRAY['fire']),
	('armarouge', ARRAY['fire', 'psychic']),
	('ceruledge', ARRAY['fire', 'ghost']),
	('tadbulb', ARRAY['electric']),
	('bellibolt', ARRAY['electric']),
	('wattrel', ARRAY['electric', 'flying']),
	('kilowattrel', ARRAY['electric', 'flying']),
	('maschiff', ARRAY['dark']),
	('mabosstiff', ARRAY['dark']),
	('shroodle', ARRAY['poison', 'normal']),
	('grafaiai', ARRAY['poison', 'normal']),
	('bramblin', ARRAY['grass', 'ghost']),
	('brambleghast', ARRAY['grass', 'ghost']),
	('toedscool', ARRAY['ground', 'grass']),
	('toedscruel', ARRAY['ground', 'grass']),
	('klawf', ARRAY['rock']),
	('capsakid', ARRAY['grass']),
	('scovillain', ARRAY['grass', 'fire']),
	('rellor', ARRAY['bug']),
	('rabsca', ARRAY['bug', 'psychic']),
	('flittle', ARRAY['psychic']),
	('espathra', ARRAY['psychic']),
	('tinkatink', ARRAY['fairy', 'steel']),
	('tinkatuff', ARRAY['fairy', 'steel']),
	('tinkaton', ARRAY['fairy', 'steel']),
	('wiglett', ARRAY['water']),
	('wugtrio', ARRAY['water']),
	('bombirdier', ARRAY['flying', 'dark']),
	('finizen', ARRAY['water']),
	('palafin', ARRAY['water']),
	('varoom', ARRAY['steel', 'poison']),
	('revavroom', ARRAY['steel', 'poison']),
	('cyclizar', ARRAY['dragon', 'normal']),
	('orthworm', ARRAY['steel']),
	('glimmet', ARRAY['rock', 'poison']),
	('glimmora', ARRAY['rock', 'poison']),
	('greavard', ARRAY['ghost']),
	('houndstone', ARRAY['ghost']),
	('flamigo', ARRAY['flying', 'fighting']),
	('cetoddle', ARRAY['ice']),
	('cetitan', ARRAY['ice']),
	('veluza', ARRAY['water', 'psychic']),
	('dondozo', ARRAY['water']),
	('tatsugiri', ARRAY['dragon', 'water']),
	('annihilape', ARRAY['fighting', 'ghost']),
	('clodsire', ARRAY['poison', 'ground']),
	('farigiraf', ARRAY['normal', 'psychic']),
	('dudunsparce', ARRAY['normal']),
	('kingambit', ARRAY['dark', 'steel']),
	('great-tusk', ARRAY['ground', 'fighting']),
	('scream-tail', ARRAY['fairy', 'psychic']),
	('brute-bonnet', ARRAY['grass', 'dark']),
	('flutter-mane', ARRAY['ghost', 'fairy']),
	('slither-wing', ARRAY['bug', 'fighting']),
	('sandy-shocks', ARRAY['electric', 'ground']),
	('iron-treads', ARRAY['ground', 'steel']),
	('iron-bundle', ARRAY['ice', 'water']),
	('iron-hands', ARRAY['fighting', 'electric']),
	('iron-jugulis', ARRAY['dark', 'flying']),
	('iron-moth', ARRAY['fire', 'poison']),
	('iron-thorns', ARRAY['rock', 'electric']),
	('frigibax', ARRAY['dragon', 'ice']),
	('arctibax', ARRAY['dragon', 'ice']),
	('baxcalibur', ARRAY['dragon', 'ice']),
	('gimmighoul', ARRAY['ghost']),
	('gimmighoul-roaming', ARRAY['ghost']),
	('gholdengo', ARRAY['steel', 'ghost']),
	('wo-chien', ARRAY['dark', 'grass']),
	('chien-pao', ARRAY['dark', 'ice']),
	('ting-lu', ARRAY['dark', 'ground']),
	('chi-yu', ARRAY['dark', 'fire']),
	('roaring-moon', ARRAY['dragon', 'dark']),
	('iron-valiant', ARRAY['fairy', 'fighting']),
	('koraidon', ARRAY['fighting', 'dragon']),
	('miraidon', ARRAY['electric', 'dragon']),
	('walking-wake', ARRAY['water', 'dragon']),
	('iron-leaves', ARRAY['grass', 'psychic']),
	('dipplin', ARRAY['grass', 'dragon']),
	('poltchageist', ARRAY['grass', 'ghost']),
	('sinistcha', ARRAY['grass', 'ghost']),
	('okidogi', ARRAY['poison', 'fighting']),
	('munkidori', ARRAY['poison', 'psychic']),
	('fezandipiti', ARRAY['poison', 'fairy']),
	('ogerpon', ARRAY['grass']),
	('ogerpon-wellspring-mask', ARRAY['grass', 'water']),
	('ogerpon-heartflame-mask', ARRAY['grass', 'fire']),
	('ogerpon-cornerstone-mask', ARRAY['grass', 'rock']),
	('archaludon', ARRAY['steel', 'dragon']),
	('hydrapple', ARRAY['grass', 'dragon']),
	('gouging-fire', ARRAY['fire', 'dragon']),
	('raging-bolt', ARRAY['electric', 'dragon']),
	('iron-boulder', ARRAY['rock', 'psychic']),
	('iron-crown', ARRAY['steel', 'psychic']),
	('terapagos', ARRAY['normal']),
	('terapagos-terastal-form', ARRAY['normal']),
	('terapagos-stellar-form', ARRAY['normal']),
	('pecharunt', ARRAY['poison', 'ghost'])
ON CONFLICT (id) DO NOTHING;