ALTER TABLE private.fakemon
	ADD COLUMN normal_portrait_filename VARCHAR(255),
	ADD COLUMN normal_sprite_filename VARCHAR(255),
	ADD COLUMN shiny_portrait_filename VARCHAR(255),
	ADD COLUMN shiny_sprite_filename VARCHAR(255),
	ADD COLUMN art_attribution_name VARCHAR(255),
	ADD COLUMN art_attribution_href VARCHAR(255),
	ADD COLUMN shiny_hue_rotation INT DEFAULT 0;

DROP FUNCTION get_fakemon;

CREATE OR REPLACE FUNCTION get_fakemon(_read_key VARCHAR(32))
RETURNS TABLE (
	id UUID,
	read_key VARCHAR(32),
	species_name VARCHAR(255),
	type VARCHAR(255)[],
	size VARCHAR(255),
	sr VARCHAR(255),
	min_level INT,
	egg_groups VARCHAR(255)[],
	gender VARCHAR(255),
	description TEXT,
	ac INT,
	hp INT,
	hit_dice VARCHAR(4),
	speed_walking INT,
	speed_climbing INT,
	speed_swimming INT,
	speed_flying INT,
	speed_hover INT,
	speed_burrowing INT,
	sense_darkvision INT,
	sense_blindsight INT,
	sense_tremorsense INT,
	sense_truesight INT,
	strength INT,
	dexterity INT,
	constitution INT,
	intelligence INT,
	wisdom INT,
	charisma INT,
	prof_athletics BOOLEAN,
	prof_acrobatics BOOLEAN,
	prof_sleight_of_hand BOOLEAN,
	prof_stealth BOOLEAN,
	prof_arcana BOOLEAN,
	prof_history BOOLEAN,
	prof_investigation BOOLEAN,
	prof_nature BOOLEAN,
	prof_religion BOOLEAN,
	prof_animal_handling BOOLEAN,
	prof_insight BOOLEAN,
	prof_medicine BOOLEAN,
	prof_perception BOOLEAN,
	prof_survival BOOLEAN,
	prof_deception BOOLEAN,
	prof_intimidation BOOLEAN,
	prof_performance BOOLEAN,
	prof_persuasion BOOLEAN,
	save_str BOOLEAN,
	save_dex BOOLEAN,
	save_con BOOLEAN,
	save_int BOOLEAN,
	save_wis BOOLEAN,
	save_cha BOOLEAN,
	abilities VARCHAR(255)[],
	hidden_abilities VARCHAR(255)[],
	moves_start VARCHAR(255)[],
	moves_level2 VARCHAR(255)[],
	moves_level6 VARCHAR(255)[],
	moves_level10 VARCHAR(255)[],
	moves_level14 VARCHAR(255)[],
	moves_level18 VARCHAR(255)[],
	moves_egg VARCHAR(255)[],
	moves_tm INT[],
	normal_portrait_filename VARCHAR(255),
	normal_sprite_filename VARCHAR(255),
	shiny_portrait_filename VARCHAR(255),
	shiny_sprite_filename VARCHAR(255),
	art_attribution_name VARCHAR(255),
	art_attribution_href VARCHAR(255),
	shiny_hue_rotation INT
) AS $$
BEGIN
	RETURN QUERY SELECT
		fakemon.id,
		fakemon.read_key,
		fakemon.species_name,
		fakemon.type,
		fakemon.size,
		fakemon.sr,
		fakemon.min_level,
		fakemon.egg_groups,
		fakemon.gender,
		fakemon.description,
		fakemon.ac,
		fakemon.hp,
		fakemon.hit_dice,
		fakemon.speed_walking,
		fakemon.speed_climbing,
		fakemon.speed_swimming,
		fakemon.speed_flying,
		fakemon.speed_hover,
		fakemon.speed_burrowing,
		fakemon.sense_darkvision,
		fakemon.sense_blindsight,
		fakemon.sense_tremorsense,
		fakemon.sense_truesight,
		fakemon.strength,
		fakemon.dexterity,
		fakemon.constitution,
		fakemon.intelligence,
		fakemon.wisdom,
		fakemon.charisma,
		fakemon.prof_athletics,
		fakemon.prof_acrobatics,
		fakemon.prof_sleight_of_hand,
		fakemon.prof_stealth,
		fakemon.prof_arcana,
		fakemon.prof_history,
		fakemon.prof_investigation,
		fakemon.prof_nature,
		fakemon.prof_religion,
		fakemon.prof_animal_handling,
		fakemon.prof_insight,
		fakemon.prof_medicine,
		fakemon.prof_perception,
		fakemon.prof_survival,
		fakemon.prof_deception,
		fakemon.prof_intimidation,
		fakemon.prof_performance,
		fakemon.prof_persuasion,
		fakemon.save_str,
		fakemon.save_dex,
		fakemon.save_con,
		fakemon.save_int,
		fakemon.save_wis,
		fakemon.save_cha,
		fakemon.abilities,
		fakemon.hidden_abilities,
		fakemon.moves_start,
		fakemon.moves_level2,
		fakemon.moves_level6,
		fakemon.moves_level10,
		fakemon.moves_level14,
		fakemon.moves_level18,
		fakemon.moves_egg,
		fakemon.moves_tm,
		fakemon.normal_portrait_filename,
		fakemon.normal_sprite_filename,
		fakemon.shiny_portrait_filename,
		fakemon.shiny_sprite_filename,
		fakemon.art_attribution_name,
		fakemon.art_attribution_href,
		fakemon.shiny_hue_rotation
	FROM private.fakemon WHERE fakemon.read_key = _read_key;
END $$ LANGUAGE PLPGSQL STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION new_fakemon(
	_species_name VARCHAR(255),
	_type VARCHAR(255)[],
	_size VARCHAR(255),
	_sr VARCHAR(255),
	_min_level INT,
	_egg_groups VARCHAR(255)[],
	_gender VARCHAR(255),
	_description TEXT,
	_ac INT,
	_hp INT,
	_hit_dice VARCHAR(4),
	_speed_walking INT,
	_speed_climbing INT,
	_speed_swimming INT,
	_speed_flying INT,
	_speed_hover INT,
	_speed_burrowing INT,
	_sense_darkvision INT,
	_sense_blindsight INT,
	_sense_tremorsense INT,
	_sense_truesight INT,
	_strength INT,
	_dexterity INT,
	_constitution INT,
	_intelligence INT,
	_wisdom INT,
	_charisma INT,
	_prof_athletics BOOLEAN,
	_prof_acrobatics BOOLEAN,
	_prof_sleight_of_hand BOOLEAN,
	_prof_stealth BOOLEAN,
	_prof_arcana BOOLEAN,
	_prof_history BOOLEAN,
	_prof_investigation BOOLEAN,
	_prof_nature BOOLEAN,
	_prof_religion BOOLEAN,
	_prof_animal_handling BOOLEAN,
	_prof_insight BOOLEAN,
	_prof_medicine BOOLEAN,
	_prof_perception BOOLEAN,
	_prof_survival BOOLEAN,
	_prof_deception BOOLEAN,
	_prof_intimidation BOOLEAN,
	_prof_performance BOOLEAN,
	_prof_persuasion BOOLEAN,
	_save_str BOOLEAN,
	_save_dex BOOLEAN,
	_save_con BOOLEAN,
	_save_int BOOLEAN,
	_save_wis BOOLEAN,
	_save_cha BOOLEAN,
	_abilities VARCHAR(255)[],
	_hidden_abilities VARCHAR(255)[],
	_moves_start VARCHAR(255)[],
	_moves_level2 VARCHAR(255)[],
	_moves_level6 VARCHAR(255)[],
	_moves_level10 VARCHAR(255)[],
	_moves_level14 VARCHAR(255)[],
	_moves_level18 VARCHAR(255)[],
	_moves_egg VARCHAR(255)[],
	_moves_tm INT[],
	_art_attribution_name VARCHAR(255),
	_art_attribution_href VARCHAR(255),
	_shiny_hue_rotation INT,
	OUT ret_id UUID,
	OUT ret_read_key VARCHAR(32),
	OUT ret_write_key VARCHAR(32)
) AS $$
BEGIN
	INSERT INTO private.fakemon (
		species_name,
		type,
		size,
		sr,
		min_level,
		egg_groups,
		gender,
		description,
		ac,
		hp,
		hit_dice,
		speed_walking,
		speed_climbing,
		speed_swimming,
		speed_flying,
		speed_hover,
		speed_burrowing,
		sense_darkvision,
		sense_blindsight,
		sense_tremorsense,
		sense_truesight,
		strength,
		dexterity,
		constitution,
		intelligence,
		wisdom,
		charisma,
		prof_athletics,
		prof_acrobatics,
		prof_sleight_of_hand,
		prof_stealth,
		prof_arcana,
		prof_history,
		prof_investigation,
		prof_nature,
		prof_religion,
		prof_animal_handling,
		prof_insight,
		prof_medicine,
		prof_perception,
		prof_survival,
		prof_deception,
		prof_intimidation,
		prof_performance,
		prof_persuasion,
		save_str,
		save_dex,
		save_con,
		save_int,
		save_wis,
		save_cha,
		abilities,
		hidden_abilities,
		moves_start,
		moves_level2,
		moves_level6,
		moves_level10,
		moves_level14,
		moves_level18,
		moves_egg,
		moves_tm,
		art_attribution_name,
		art_attribution_href,
		shiny_hue_rotation
	) VALUES (
		_species_name,
		_type,
		_size,
		_sr,
		_min_level,
		_egg_groups,
		_gender,
		_description,
		_ac,
		_hp,
		_hit_dice,
		_speed_walking,
		_speed_climbing,
		_speed_swimming,
		_speed_flying,
		_speed_hover,
		_speed_burrowing,
		_sense_darkvision,
		_sense_blindsight,
		_sense_tremorsense,
		_sense_truesight,
		_strength,
		_dexterity,
		_constitution,
		_intelligence,
		_wisdom,
		_charisma,
		_prof_athletics,
		_prof_acrobatics,
		_prof_sleight_of_hand,
		_prof_stealth,
		_prof_arcana,
		_prof_history,
		_prof_investigation,
		_prof_nature,
		_prof_religion,
		_prof_animal_handling,
		_prof_insight,
		_prof_medicine,
		_prof_perception,
		_prof_survival,
		_prof_deception,
		_prof_intimidation,
		_prof_performance,
		_prof_persuasion,
		_save_str,
		_save_dex,
		_save_con,
		_save_int,
		_save_wis,
		_save_cha,
		_abilities,
		_hidden_abilities,
		_moves_start,
		_moves_level2,
		_moves_level6,
		_moves_level10,
		_moves_level14,
		_moves_level18,
		_moves_egg,
		_moves_tm,
		_art_attribution_name,
		_art_attribution_href,
		_shiny_hue_rotation
	) RETURNING id, read_key, write_key INTO ret_id, ret_read_key, ret_write_key;
END $$ LANGUAGE PLPGSQL VOLATILE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION update_fakemon(
	_write_key VARCHAR(32),
	_species_name VARCHAR(255),
	_type VARCHAR(255)[],
	_size VARCHAR(255),
	_sr VARCHAR(255),
	_min_level INT,
	_egg_groups VARCHAR(255)[],
	_gender VARCHAR(255),
	_description TEXT,
	_ac INT,
	_hp INT,
	_hit_dice VARCHAR(4),
	_speed_walking INT,
	_speed_climbing INT,
	_speed_swimming INT,
	_speed_flying INT,
	_speed_hover INT,
	_speed_burrowing INT,
	_sense_darkvision INT,
	_sense_blindsight INT,
	_sense_tremorsense INT,
	_sense_truesight INT,
	_strength INT,
	_dexterity INT,
	_constitution INT,
	_intelligence INT,
	_wisdom INT,
	_charisma INT,
	_prof_athletics BOOLEAN,
	_prof_acrobatics BOOLEAN,
	_prof_sleight_of_hand BOOLEAN,
	_prof_stealth BOOLEAN,
	_prof_arcana BOOLEAN,
	_prof_history BOOLEAN,
	_prof_investigation BOOLEAN,
	_prof_nature BOOLEAN,
	_prof_religion BOOLEAN,
	_prof_animal_handling BOOLEAN,
	_prof_insight BOOLEAN,
	_prof_medicine BOOLEAN,
	_prof_perception BOOLEAN,
	_prof_survival BOOLEAN,
	_prof_deception BOOLEAN,
	_prof_intimidation BOOLEAN,
	_prof_performance BOOLEAN,
	_prof_persuasion BOOLEAN,
	_save_str BOOLEAN,
	_save_dex BOOLEAN,
	_save_con BOOLEAN,
	_save_int BOOLEAN,
	_save_wis BOOLEAN,
	_save_cha BOOLEAN,
	_abilities VARCHAR(255)[],
	_hidden_abilities VARCHAR(255)[],
	_moves_start VARCHAR(255)[],
	_moves_level2 VARCHAR(255)[],
	_moves_level6 VARCHAR(255)[],
	_moves_level10 VARCHAR(255)[],
	_moves_level14 VARCHAR(255)[],
	_moves_level18 VARCHAR(255)[],
	_moves_egg VARCHAR(255)[],
	_moves_tm INT[],
	_art_attribution_name VARCHAR(255),
	_art_attribution_href VARCHAR(255),
	_shiny_hue_rotation INT
) RETURNS INT AS $$
DECLARE affected_rows INT;
BEGIN
	UPDATE private.fakemon SET
		species_name = _species_name,
		type = _type,
		size = _size,
		sr = _sr,
		min_level = _min_level,
		egg_groups = _egg_groups,
		gender = _gender,
		description = _description,
		ac = _ac,
		hp = _hp,
		hit_dice = _hit_dice,
		speed_walking = _speed_walking,
		speed_climbing = _speed_climbing,
		speed_swimming = _speed_swimming,
		speed_flying = _speed_flying,
		speed_hover = _speed_hover,
		speed_burrowing = _speed_burrowing,
		sense_darkvision = _sense_darkvision,
		sense_blindsight = _sense_blindsight,
		sense_tremorsense = _sense_tremorsense,
		sense_truesight = _sense_truesight,
		strength = _strength,
		dexterity = _dexterity,
		constitution = _constitution,
		intelligence = _intelligence,
		wisdom = _wisdom,
		charisma = _charisma,
		prof_athletics = _prof_athletics,
		prof_acrobatics = _prof_acrobatics,
		prof_sleight_of_hand = _prof_sleight_of_hand,
		prof_stealth = _prof_stealth,
		prof_arcana = _prof_arcana,
		prof_history = _prof_history,
		prof_investigation = _prof_investigation,
		prof_nature = _prof_nature,
		prof_religion = _prof_religion,
		prof_animal_handling = _prof_animal_handling,
		prof_insight = _prof_insight,
		prof_medicine = _prof_medicine,
		prof_perception = _prof_perception,
		prof_survival = _prof_survival,
		prof_deception = _prof_deception,
		prof_intimidation = _prof_intimidation,
		prof_performance = _prof_performance,
		prof_persuasion = _prof_persuasion,
		save_str = _save_str,
		save_dex = _save_dex,
		save_con = _save_con,
		save_int = _save_int,
		save_wis = _save_wis,
		save_cha = _save_cha,
		abilities = _abilities,
		hidden_abilities = _hidden_abilities,
		moves_start = _moves_start,
		moves_level2 = _moves_level2,
		moves_level6 = _moves_level6,
		moves_level10 = _moves_level10,
		moves_level14 = _moves_level14,
		moves_level18 = _moves_level18,
		moves_egg = _moves_egg,
		moves_tm = _moves_tm,
		art_attribution_name = _art_attribution_name,
		art_attribution_href = _art_attribution_href,
		shiny_hue_rotation = _shiny_hue_rotation
	WHERE
		write_key = _write_key;
	
	GET DIAGNOSTICS affected_rows := ROW_COUNT;

	RETURN affected_rows;
END $$ LANGUAGE PLPGSQL VOLATILE SECURITY DEFINER;

CREATE TYPE fakemon_filenames_result AS (
	normal_portrait_filename VARCHAR(255),
	normal_sprite_filename VARCHAR(255),
	shiny_portrait_filename VARCHAR(255),
	shiny_sprite_filename VARCHAR(255)
);

CREATE OR REPLACE FUNCTION new_fakemon_avatar_filenames(
	_write_key VARCHAR(32),
	_normal_portrait_extension VARCHAR(32) DEFAULT NULL,
	_normal_sprite_extension VARCHAR(32) DEFAULT NULL,
	_shiny_portrait_extension VARCHAR(32) DEFAULT NULL,
	_shiny_sprite_extension VARCHAR(32) DEFAULT NULL
) RETURNS fakemon_filenames_result AS $$
DECLARE
	_uuid uuid;
	_normal_portrait_filename VARCHAR(255) := NULL;
	_normal_sprite_filename VARCHAR(255) := NULL;
	_shiny_portrait_filename VARCHAR(255) := NULL;
	_shiny_sprite_filename VARCHAR(255) := NULL;
	_result fakemon_filenames_result;
BEGIN
	IF _normal_portrait_extension IS NOT NULL THEN
		_uuid := uuid_generate_v4();
		_normal_portrait_filename := _uuid || _normal_portrait_extension;
	END IF;
	
	IF _normal_sprite_extension IS NOT NULL THEN
		_uuid := uuid_generate_v4();
		_normal_sprite_filename := _uuid || _normal_sprite_extension;
	END IF;
	
	IF _shiny_portrait_extension IS NOT NULL THEN
		_uuid := uuid_generate_v4();
		_shiny_portrait_filename := _uuid || _shiny_portrait_extension;
	END IF;
	
	IF _shiny_sprite_extension IS NOT NULL THEN
		_uuid := uuid_generate_v4();
		_shiny_sprite_filename := _uuid || _shiny_sprite_extension;
	END IF;

	UPDATE private.fakemon
	SET 
		normal_portrait_filename = COALESCE(_normal_portrait_filename, normal_portrait_filename),
		normal_sprite_filename = COALESCE(_normal_sprite_filename, normal_sprite_filename),
		shiny_portrait_filename = COALESCE(_shiny_portrait_filename, shiny_portrait_filename),
		shiny_sprite_filename = COALESCE(_shiny_sprite_filename, shiny_sprite_filename)
	WHERE write_key = _write_key;

	_result.normal_portrait_filename := _normal_portrait_filename;
	_result.normal_sprite_filename := _normal_sprite_filename;
	_result.shiny_portrait_filename := _shiny_portrait_filename;
	_result.shiny_sprite_filename := _shiny_sprite_filename;

	RETURN _result;
END $$ LANGUAGE PLPGSQL VOLATILE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION remove_fakemon_avatars(
	_write_key VARCHAR(32),
	_remove_normal_portrait BOOLEAN DEFAULT FALSE,
	_remove_normal_sprite BOOLEAN DEFAULT FALSE,
	_remove_shiny_portrait BOOLEAN DEFAULT FALSE,
	_remove_shiny_sprite BOOLEAN DEFAULT FALSE
) RETURNS INT AS $$
DECLARE 
	affected_rows INT;
BEGIN
	UPDATE private.fakemon
	SET 
		normal_portrait_filename = CASE 
			WHEN _remove_normal_portrait THEN NULL 
			ELSE normal_portrait_filename 
		END,
		normal_sprite_filename = CASE 
			WHEN _remove_normal_sprite THEN NULL 
			ELSE normal_sprite_filename 
		END,
		shiny_portrait_filename = CASE 
			WHEN _remove_shiny_portrait THEN NULL 
			ELSE shiny_portrait_filename 
		END,
		shiny_sprite_filename = CASE 
			WHEN _remove_shiny_sprite THEN NULL 
			ELSE shiny_sprite_filename 
		END
	WHERE write_key = _write_key;
	
	GET DIAGNOSTICS affected_rows := ROW_COUNT;
	RETURN affected_rows;
END $$ LANGUAGE PLPGSQL VOLATILE SECURITY DEFINER;
