ALTER TABLE private.trainers
	ADD COLUMN tags VARCHAR(255)[] DEFAULT '{}';

DROP FUNCTION get_trainer;

CREATE OR REPLACE FUNCTION get_trainer(_read_key VARCHAR(32))
RETURNS TABLE (
	id uuid,
	read_key VARCHAR(32),
	name VARCHAR(255),
	description TEXT,
	level INT,
	ac INT,
	hp_cur INT,
	hp_max INT,
	hit_dice_cur INT,
	hit_dice_max INT,
	strength INT,
	dexterity INT,
	constitution INT,
	intelligence INT,
	wisdom INT,
	charisma INT,
	prof_athletics BOOLEAN,
	prof_acrobatics BOOLEAN,
	prof_sleight_of_hand BOOLEAN,
	prof_stealth BOOLEAN,
	prof_arcana BOOLEAN,
	prof_history BOOLEAN,
	prof_investigation BOOLEAN,
	prof_nature BOOLEAN,
	prof_religion BOOLEAN,
	prof_animal_handling BOOLEAN,
	prof_insight BOOLEAN,
	prof_medicine BOOLEAN,
	prof_perception BOOLEAN,
	prof_survival BOOLEAN,
	prof_deception BOOLEAN,
	prof_intimidation BOOLEAN,
	prof_performance BOOLEAN,
	prof_persuasion BOOLEAN,
	save_str BOOLEAN,
	save_dex BOOLEAN,
	save_con BOOLEAN,
	save_int BOOLEAN,
	save_wis BOOLEAN,
	save_cha BOOLEAN,
	species VARCHAR(255),
	gender VARCHAR(255),
	age INT,
	home_region VARCHAR(255),
	background VARCHAR(255),
	avatar_filename VARCHAR(255),
	money INT,
	special_normal INT,
	special_fighting INT,
	special_flying INT,
	special_poison INT,
	special_ground INT,
	special_rock INT,
	special_bug INT,
	special_ghost INT,
	special_steel INT,
	special_fire INT,
	special_water INT,
	special_grass INT,
	special_electric INT,
	special_psychic INT,
	special_ice INT,
	special_dragon INT,
	special_dark INT,
	special_fairy INT,
	path_name VARCHAR(255),
	path_resource INT,
	path_rank_1_name VARCHAR(255),
	path_rank_1_desc TEXT,
	path_rank_2_name VARCHAR(255),
	path_rank_2_desc TEXT,
	path_rank_3_name VARCHAR(255),
	path_rank_3_desc TEXT,
	path_rank_4_name VARCHAR(255),
	path_rank_4_desc TEXT,
	rank_athletics INT,
	rank_acrobatics INT,
	rank_sleight_of_hand INT,
	rank_stealth INT,
	rank_arcana INT,
	rank_history INT,
	rank_investigation INT,
	rank_nature INT,
	rank_religion INT,
	rank_animal_handling INT,
	rank_insight INT,
	rank_medicine INT,
	rank_perception INT,
	rank_survival INT,
	rank_deception INT,
	rank_intimidation INT,
	rank_performance INT,
	rank_persuasion INT,
	tags VARCHAR(255)[]
) AS $$
BEGIN
	RETURN QUERY SELECT
		trainers.id,
		trainers.read_key,
		trainers.name,
		trainers.description,
		trainers.level,
		trainers.ac,
		trainers.hp_cur,
		trainers.hp_max,
		trainers.hit_dice_cur,
		trainers.hit_dice_max,
		trainers.strength,
		trainers.dexterity,
		trainers.constitution,
		trainers.intelligence,
		trainers.wisdom,
		trainers.charisma,
		trainers.prof_athletics,
		trainers.prof_acrobatics,
		trainers.prof_sleight_of_hand,
		trainers.prof_stealth,
		trainers.prof_arcana,
		trainers.prof_history,
		trainers.prof_investigation,
		trainers.prof_nature,
		trainers.prof_religion,
		trainers.prof_animal_handling,
		trainers.prof_insight,
		trainers.prof_medicine,
		trainers.prof_perception,
		trainers.prof_survival,
		trainers.prof_deception,
		trainers.prof_intimidation,
		trainers.prof_performance,
		trainers.prof_persuasion,
		trainers.save_str,
		trainers.save_dex,
		trainers.save_con,
		trainers.save_int,
		trainers.save_wis,
		trainers.save_cha,
		trainers.species,
		trainers.gender,
		trainers.age,
		trainers.home_region,
		trainers.background,
		trainers.avatar_filename,
		trainers.money,
		trainers.special_normal,
		trainers.special_fighting,
		trainers.special_flying,
		trainers.special_poison,
		trainers.special_ground,
		trainers.special_rock,
		trainers.special_bug,
		trainers.special_ghost,
		trainers.special_steel,
		trainers.special_fire,
		trainers.special_water,
		trainers.special_grass,
		trainers.special_electric,
		trainers.special_psychic,
		trainers.special_ice,
		trainers.special_dragon,
		trainers.special_dark,
		trainers.special_fairy,
		trainers.path_name,
		trainers.path_resource,
		trainers.path_rank_1_name,
		trainers.path_rank_1_desc,
		trainers.path_rank_2_name,
		trainers.path_rank_2_desc,
		trainers.path_rank_3_name,
		trainers.path_rank_3_desc,
		trainers.path_rank_4_name,
		trainers.path_rank_4_desc,
		trainers.rank_athletics,
		trainers.rank_acrobatics,
		trainers.rank_sleight_of_hand,
		trainers.rank_stealth,
		trainers.rank_arcana,
		trainers.rank_history,
		trainers.rank_investigation,
		trainers.rank_nature,
		trainers.rank_religion,
		trainers.rank_animal_handling,
		trainers.rank_insight,
		trainers.rank_medicine,
		trainers.rank_perception,
		trainers.rank_survival,
		trainers.rank_deception,
		trainers.rank_intimidation,
		trainers.rank_performance,
		trainers.rank_persuasion,
		trainers.tags
	FROM private.trainers WHERE trainers.read_key = _read_key;
END $$ LANGUAGE PLPGSQL STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION new_trainer(
	_name VARCHAR(255),
	_description TEXT,
	_level INT,
	_ac INT,
	_hp_cur INT,
	_hp_max INT,
	_hit_dice_cur INT,
	_hit_dice_max INT,
	_strength INT,
	_dexterity INT,
	_constitution INT,
	_intelligence INT,
	_wisdom INT,
	_charisma INT,
	_save_str BOOLEAN,
	_save_dex BOOLEAN,
	_save_con BOOLEAN,
	_save_int BOOLEAN,
	_save_wis BOOLEAN,
	_save_cha BOOLEAN,
	_species VARCHAR(255),
	_gender VARCHAR(255),
	_age INT,
	_home_region VARCHAR(255),
	_background VARCHAR(255),
	_money INT,
	_special_normal INT,
	_special_fighting INT,
	_special_flying INT,
	_special_poison INT,
	_special_ground INT,
	_special_rock INT,
	_special_bug INT,
	_special_ghost INT,
	_special_steel INT,
	_special_fire INT,
	_special_water INT,
	_special_grass INT,
	_special_electric INT,
	_special_psychic INT,
	_special_ice INT,
	_special_dragon INT,
	_special_dark INT,
	_special_fairy INT,
	_path_name VARCHAR(255),
	_path_resource INT,
	_path_rank_1_name VARCHAR(255),
	_path_rank_1_desc TEXT,
	_path_rank_2_name VARCHAR(255),
	_path_rank_2_desc TEXT,
	_path_rank_3_name VARCHAR(255),
	_path_rank_3_desc TEXT,
	_path_rank_4_name VARCHAR(255),
	_path_rank_4_desc TEXT,
	_rank_athletics INT,
	_rank_acrobatics INT,
	_rank_sleight_of_hand INT,
	_rank_stealth INT,
	_rank_arcana INT,
	_rank_history INT,
	_rank_investigation INT,
	_rank_nature INT,
	_rank_religion INT,
	_rank_animal_handling INT,
	_rank_insight INT,
	_rank_medicine INT,
	_rank_perception INT,
	_rank_survival INT,
	_rank_deception INT,
	_rank_intimidation INT,
	_rank_performance INT,
	_rank_persuasion INT,
	_tags VARCHAR(255)[],
	OUT ret_id uuid,
	OUT ret_read_key VARCHAR(32),
	OUT ret_write_key VARCHAR(32)
) AS $$
BEGIN
	INSERT INTO private.trainers (
		name,
		description,
		level,
		ac,
		hp_cur,
		hp_max,
		hit_dice_cur,
		hit_dice_max,
		strength,
		dexterity,
		constitution,
		intelligence,
		wisdom,
		charisma,
		prof_athletics,
		prof_acrobatics,
		prof_sleight_of_hand,
		prof_stealth,
		prof_arcana,
		prof_history,
		prof_investigation,
		prof_nature,
		prof_religion,
		prof_animal_handling,
		prof_insight,
		prof_medicine,
		prof_perception,
		prof_survival,
		prof_deception,
		prof_intimidation,
		prof_performance,
		prof_persuasion,
		save_str,
		save_dex,
		save_con,
		save_int,
		save_wis,
		save_cha,
		species,
		gender,
		age,
		home_region,
		background,
		money,
		special_normal,
		special_fighting,
		special_flying,
		special_poison,
		special_ground,
		special_rock,
		special_bug,
		special_ghost,
		special_steel,
		special_fire,
		special_water,
		special_grass,
		special_electric,
		special_psychic,
		special_ice,
		special_dragon,
		special_dark,
		special_fairy,
		path_name,
		path_resource,
		path_rank_1_name,
		path_rank_1_desc,
		path_rank_2_name,
		path_rank_2_desc,
		path_rank_3_name,
		path_rank_3_desc,
		path_rank_4_name,
		path_rank_4_desc,
		rank_athletics,
		rank_acrobatics,
		rank_sleight_of_hand,
		rank_stealth,
		rank_arcana,
		rank_history,
		rank_investigation,
		rank_nature,
		rank_religion,
		rank_animal_handling,
		rank_insight,
		rank_medicine,
		rank_perception,
		rank_survival,
		rank_deception,
		rank_intimidation,
		rank_performance,
		rank_persuasion,
		tags
	) VALUES (
		_name,
		_description,
		_level,
		_ac,
		_hp_cur,
		_hp_max,
		_hit_dice_cur,
		_hit_dice_max,
		_strength,
		_dexterity,
		_constitution,
		_intelligence,
		_wisdom,
		_charisma,
		_rank_athletics > 0,
		_rank_acrobatics > 0,
		_rank_sleight_of_hand > 0,
		_rank_stealth > 0,
		_rank_arcana > 0,
		_rank_history > 0,
		_rank_investigation > 0,
		_rank_nature > 0,
		_rank_religion > 0,
		_rank_animal_handling > 0,
		_rank_insight > 0,
		_rank_medicine > 0,
		_rank_perception > 0,
		_rank_survival > 0,
		_rank_deception > 0,
		_rank_intimidation > 0,
		_rank_performance > 0,
		_rank_persuasion > 0,
		_save_str,
		_save_dex,
		_save_con,
		_save_int,
		_save_wis,
		_save_cha,
		_species,
		_gender,
		_age,
		_home_region,
		_background,
		_money,
		_special_normal,
		_special_fighting,
		_special_flying,
		_special_poison,
		_special_ground,
		_special_rock,
		_special_bug,
		_special_ghost,
		_special_steel,
		_special_fire,
		_special_water,
		_special_grass,
		_special_electric,
		_special_psychic,
		_special_ice,
		_special_dragon,
		_special_dark,
		_special_fairy,
		_path_name,
		_path_resource,
		_path_rank_1_name,
		_path_rank_1_desc,
		_path_rank_2_name,
		_path_rank_2_desc,
		_path_rank_3_name,
		_path_rank_3_desc,
		_path_rank_4_name,
		_path_rank_4_desc,
		_rank_athletics,
		_rank_acrobatics,
		_rank_sleight_of_hand,
		_rank_stealth,
		_rank_arcana,
		_rank_history,
		_rank_investigation,
		_rank_nature,
		_rank_religion,
		_rank_animal_handling,
		_rank_insight,
		_rank_medicine,
		_rank_perception,
		_rank_survival,
		_rank_deception,
		_rank_intimidation,
		_rank_performance,
		_rank_persuasion,
		_tags
	) RETURNING id, read_key, write_key INTO ret_id, ret_read_key, ret_write_key;
END $$ LANGUAGE PLPGSQL VOLATILE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION update_trainer(
	_write_key VARCHAR(32),
	_name VARCHAR(255),
	_description TEXT,
	_level INT,
	_ac INT,
	_hp_cur INT,
	_hp_max INT,
	_hit_dice_cur INT,
	_hit_dice_max INT,
	_strength INT,
	_dexterity INT,
	_constitution INT,
	_intelligence INT,
	_wisdom INT,
	_charisma INT,
	_save_str BOOLEAN,
	_save_dex BOOLEAN,
	_save_con BOOLEAN,
	_save_int BOOLEAN,
	_save_wis BOOLEAN,
	_save_cha BOOLEAN,
	_species VARCHAR(255),
	_gender VARCHAR(255),
	_age INT,
	_home_region VARCHAR(255),
	_background VARCHAR(255),
	_money INT,
	_special_normal INT,
	_special_fighting INT,
	_special_flying INT,
	_special_poison INT,
	_special_ground INT,
	_special_rock INT,
	_special_bug INT,
	_special_ghost INT,
	_special_steel INT,
	_special_fire INT,
	_special_water INT,
	_special_grass INT,
	_special_electric INT,
	_special_psychic INT,
	_special_ice INT,
	_special_dragon INT,
	_special_dark INT,
	_special_fairy INT,
	_path_name VARCHAR(255),
	_path_resource INT,
	_path_rank_1_name VARCHAR(255),
	_path_rank_1_desc TEXT,
	_path_rank_2_name VARCHAR(255),
	_path_rank_2_desc TEXT,
	_path_rank_3_name VARCHAR(255),
	_path_rank_3_desc TEXT,
	_path_rank_4_name VARCHAR(255),
	_path_rank_4_desc TEXT,
	_rank_athletics INT,
	_rank_acrobatics INT,
	_rank_sleight_of_hand INT,
	_rank_stealth INT,
	_rank_arcana INT,
	_rank_history INT,
	_rank_investigation INT,
	_rank_nature INT,
	_rank_religion INT,
	_rank_animal_handling INT,
	_rank_insight INT,
	_rank_medicine INT,
	_rank_perception INT,
	_rank_survival INT,
	_rank_deception INT,
	_rank_intimidation INT,
	_rank_performance INT,
	_rank_persuasion INT,
	_tags VARCHAR(255)[]
) RETURNS INT AS $$
DECLARE affected_rows INT;
BEGIN
	UPDATE private.trainers SET
		name = _name,
		description = _description,
		level = _level,
		ac = _ac,
		hp_cur = _hp_cur,
		hp_max = _hp_max,
		hit_dice_cur = _hit_dice_cur,
		hit_dice_max = _hit_dice_max,
		strength = _strength,
		dexterity = _dexterity,
		constitution = _constitution,
		intelligence = _intelligence,
		wisdom = _wisdom,
		charisma = _charisma,
		prof_athletics = _rank_athletics > 0,
		prof_acrobatics = _rank_acrobatics > 0,
		prof_sleight_of_hand = _rank_sleight_of_hand > 0,
		prof_stealth = _rank_stealth > 0,
		prof_arcana = _rank_arcana > 0,
		prof_history = _rank_history > 0,
		prof_investigation = _rank_investigation > 0,
		prof_nature = _rank_nature > 0,
		prof_religion = _rank_religion > 0,
		prof_animal_handling = _rank_animal_handling > 0,
		prof_insight = _rank_insight > 0,
		prof_medicine = _rank_medicine > 0,
		prof_perception = _rank_perception > 0,
		prof_survival = _rank_survival > 0,
		prof_deception = _rank_deception > 0,
		prof_intimidation = _rank_intimidation > 0,
		prof_performance = _rank_performance > 0,
		prof_persuasion = _rank_persuasion > 0,
		save_str = _save_str,
		save_dex = _save_dex,
		save_con = _save_con,
		save_int = _save_int,
		save_wis = _save_wis,
		save_cha = _save_cha,
		species = _species,
		gender = _gender,
		age = _age,
		home_region = _home_region,
		background = _background,
		money = _money,
		special_normal = _special_normal,
		special_fighting = _special_fighting,
		special_flying = _special_flying,
		special_poison = _special_poison,
		special_ground = _special_ground,
		special_rock = _special_rock,
		special_bug = _special_bug,
		special_ghost = _special_ghost,
		special_steel = _special_steel,
		special_fire = _special_fire,
		special_water = _special_water,
		special_grass = _special_grass,
		special_electric = _special_electric,
		special_psychic = _special_psychic,
		special_ice = _special_ice,
		special_dragon = _special_dragon,
		special_dark = _special_dark,
		special_fairy = _special_fairy,
		path_name = _path_name,
		path_resource = _path_resource,
		path_rank_1_name = _path_rank_1_name,
		path_rank_1_desc = _path_rank_1_desc,
		path_rank_2_name = _path_rank_2_name,
		path_rank_2_desc = _path_rank_2_desc,
		path_rank_3_name = _path_rank_3_name,
		path_rank_3_desc = _path_rank_3_desc,
		path_rank_4_name = _path_rank_4_name,
		path_rank_4_desc = _path_rank_4_desc,
		rank_athletics = _rank_athletics,
		rank_acrobatics = _rank_acrobatics,
		rank_sleight_of_hand = _rank_sleight_of_hand,
		rank_stealth = _rank_stealth,
		rank_arcana = _rank_arcana,
		rank_history = _rank_history,
		rank_investigation = _rank_investigation,
		rank_nature = _rank_nature,
		rank_religion = _rank_religion,
		rank_animal_handling = _rank_animal_handling,
		rank_insight = _rank_insight,
		rank_medicine = _rank_medicine,
		rank_perception = _rank_perception,
		rank_survival = _rank_survival,
		rank_deception = _rank_deception,
		rank_intimidation = _rank_intimidation,
		rank_performance = _rank_performance,
		rank_persuasion = _rank_persuasion,
		tags = _tags
	WHERE
		write_key = _write_key;
	
	GET DIAGNOSTICS affected_rows := ROW_COUNT;

	RETURN affected_rows;
END $$ LANGUAGE PLPGSQL VOLATILE SECURITY DEFINER;

---------------------------------------------

ALTER TABLE private.pokemon
	ADD COLUMN tags VARCHAR(255)[] DEFAULT '{}';

CREATE OR REPLACE FUNCTION add_pokemon(
	_write_key VARCHAR(32),
	_nickname VARCHAR(255),
	_species VARCHAR(255),
	_type VARCHAR(255)[],
	_nature VARCHAR(255),
	_level INT,
	_gender VARCHAR(255),
	_strength INT,
	_dexterity INT,
	_constitution INT,
	_intelligence INT,
	_wisdom INT,
	_charisma INT,
	_ac INT,
	_hp_cur INT,
	_hp_max INT,
	_hit_dice_cur INT,
	_hit_dice_max INT,
	_save_str BOOLEAN,
	_save_dex BOOLEAN,
	_save_con BOOLEAN,
	_save_int BOOLEAN,
	_save_wis BOOLEAN,
	_save_cha BOOLEAN,
	_ability VARCHAR(255),
	_abilities JSON,
	_notes TEXT,
	_tera_type VARCHAR(255),
	_exp INT,
	_status VARCHAR(255),
	_held_item VARCHAR(255),
	_is_shiny BOOLEAN,
	_custom_size VARCHAR(255),
	_hit_dice_size VARCHAR(4),
	_speed_walking INT,
	_speed_climbing INT,
	_speed_swimming INT,
	_speed_flying INT,
	_speed_hover INT,
	_speed_burrowing INT,
	_sense_darkvision INT,
	_sense_blindsight INT,
	_sense_tremorsense INT,
	_sense_truesight INT,
	_bond_level INT,
	_bond_points_cur INT,
	_bond_points_max INT,
	_rank_athletics INT,
	_rank_acrobatics INT,
	_rank_sleight_of_hand INT,
	_rank_stealth INT,
	_rank_arcana INT,
	_rank_history INT,
	_rank_investigation INT,
	_rank_nature INT,
	_rank_religion INT,
	_rank_animal_handling INT,
	_rank_insight INT,
	_rank_medicine INT,
	_rank_perception INT,
	_rank_survival INT,
	_rank_deception INT,
	_rank_intimidation INT,
	_rank_performance INT,
	_rank_persuasion INT,
	_rank INT,
	_stab_base VARCHAR(255),
	_stab_bonus INT,
	_tags VARCHAR(255)[]
) RETURNS INT AS $$
DECLARE ret_id INT;
BEGIN
	INSERT INTO private.pokemon (
		trainer_id,
		nickname,
		species,
		type,
		nature,
		level,
		gender,
		strength,
		dexterity,
		constitution,
		intelligence,
		wisdom,
		charisma,
		ac,
		hp_cur,
		hp_max,
		hit_dice_cur,
		hit_dice_max,
		prof_athletics,
		prof_acrobatics,
		prof_sleight_of_hand,
		prof_stealth,
		prof_arcana,
		prof_history,
		prof_investigation,
		prof_nature,
		prof_religion,
		prof_animal_handling,
		prof_insight,
		prof_medicine,
		prof_perception,
		prof_survival,
		prof_deception,
		prof_intimidation,
		prof_performance,
		prof_persuasion,
		save_str,
		save_dex,
		save_con,
		save_int,
		save_wis,
		save_cha,
		ability,
		abilities,
		notes,
		tera_type,
		exp,
		status,
		held_item,
		is_shiny,
		custom_size,
		hit_dice_size,
		speed_walking,
		speed_climbing,
		speed_swimming,
		speed_flying,
		speed_hover,
		speed_burrowing,
		sense_darkvision,
		sense_blindsight,
		sense_tremorsense,
		sense_truesight,
		bond_level,
		bond_points_cur,
		bond_points_max,
		rank_athletics,
		rank_acrobatics,
		rank_sleight_of_hand,
		rank_stealth,
		rank_arcana,
		rank_history,
		rank_investigation,
		rank_nature,
		rank_religion,
		rank_animal_handling,
		rank_insight,
		rank_medicine,
		rank_perception,
		rank_survival,
		rank_deception,
		rank_intimidation,
		rank_performance,
		rank_persuasion,
		rank,
		stab_base,
		stab_bonus,
		tags
	) VALUES (
		(SELECT id FROM private.trainers WHERE write_key = _write_key),
		_nickname,
		_species,
		_type,
		_nature,
		_level,
		_gender,
		_strength,
		_dexterity,
		_constitution,
		_intelligence,
		_wisdom,
		_charisma,
		_ac,
		_hp_cur,
		_hp_max,
		_hit_dice_cur,
		_hit_dice_max,
		_rank_athletics > 0,
		_rank_acrobatics > 0,
		_rank_sleight_of_hand > 0,
		_rank_stealth > 0,
		_rank_arcana > 0,
		_rank_history > 0,
		_rank_investigation > 0,
		_rank_nature > 0,
		_rank_religion > 0,
		_rank_animal_handling > 0,
		_rank_insight > 0,
		_rank_medicine > 0,
		_rank_perception > 0,
		_rank_survival > 0,
		_rank_deception > 0,
		_rank_intimidation > 0,
		_rank_performance > 0,
		_rank_persuasion > 0,
		_save_str,
		_save_dex,
		_save_con,
		_save_int,
		_save_wis,
		_save_cha,
		_ability,
		_abilities,
		_notes,
		_tera_type,
		_exp,
		_status,
		_held_item,
		_is_shiny,
		_custom_size,
		_hit_dice_size,
		_speed_walking,
		_speed_climbing,
		_speed_swimming,
		_speed_flying,
		_speed_hover,
		_speed_burrowing,
		_sense_darkvision,
		_sense_blindsight,
		_sense_tremorsense,
		_sense_truesight,
		_bond_level,
		_bond_points_cur,
		_bond_points_max,
		_rank_athletics,
		_rank_acrobatics,
		_rank_sleight_of_hand,
		_rank_stealth,
		_rank_arcana,
		_rank_history,
		_rank_investigation,
		_rank_nature,
		_rank_religion,
		_rank_animal_handling,
		_rank_insight,
		_rank_medicine,
		_rank_perception,
		_rank_survival,
		_rank_deception,
		_rank_intimidation,
		_rank_performance,
		_rank_persuasion,
		_rank,
		_stab_base,
		_stab_bonus,
		_tags
	) RETURNING id INTO ret_id;

	RETURN ret_id;
END $$ LANGUAGE PLPGSQL VOLATILE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION update_pokemon(
	_write_key VARCHAR(32),
	_id INT,
	_species VARCHAR(255),
	_nickname VARCHAR(255),
	_type VARCHAR(255)[],
	_nature VARCHAR(255),
	_level INT,
	_gender VARCHAR(255),
	_strength INT,
	_dexterity INT,
	_constitution INT,
	_intelligence INT,
	_wisdom INT,
	_charisma INT,
	_ac INT,
	_hp_cur INT,
	_hp_max INT,
	_hit_dice_cur INT,
	_hit_dice_max INT,
	_save_str BOOLEAN,
	_save_dex BOOLEAN,
	_save_con BOOLEAN,
	_save_int BOOLEAN,
	_save_wis BOOLEAN,
	_save_cha BOOLEAN,
	_ability VARCHAR(255),
	_abilities JSON,
	_notes TEXT,
	_tera_type VARCHAR(255),
	_exp INT,
	_status VARCHAR(255),
	_held_item VARCHAR(255),
	_is_shiny BOOLEAN,
	_custom_size VARCHAR(255),
	_hit_dice_size VARCHAR(4),
	_speed_walking INT,
	_speed_climbing INT,
	_speed_swimming INT,
	_speed_flying INT,
	_speed_hover INT,
	_speed_burrowing INT,
	_sense_darkvision INT,
	_sense_blindsight INT,
	_sense_tremorsense INT,
	_sense_truesight INT,
	_bond_level INT,
	_bond_points_cur INT,
	_bond_points_max INT,
	_rank_athletics INT,
	_rank_acrobatics INT,
	_rank_sleight_of_hand INT,
	_rank_stealth INT,
	_rank_arcana INT,
	_rank_history INT,
	_rank_investigation INT,
	_rank_nature INT,
	_rank_religion INT,
	_rank_animal_handling INT,
	_rank_insight INT,
	_rank_medicine INT,
	_rank_perception INT,
	_rank_survival INT,
	_rank_deception INT,
	_rank_intimidation INT,
	_rank_performance INT,
	_rank_persuasion INT,
	_stab_base VARCHAR(255),
	_stab_bonus INT,
	_tags VARCHAR(255)[]
) RETURNS INT AS $$
DECLARE affected_rows INT;
BEGIN
	UPDATE private.pokemon p SET
		species = _species,
		nickname = _nickname,
		nature = _nature,
		type = _type,
		level = _level,
		gender = _gender,
		strength = _strength,
		dexterity = _dexterity,
		constitution = _constitution,
		intelligence = _intelligence,
		wisdom = _wisdom,
		charisma = _charisma,
		ac = _ac,
		hp_cur = _hp_cur,
		hp_max = _hp_max,
		hit_dice_cur = _hit_dice_cur,
		hit_dice_max = _hit_dice_max,
		prof_athletics = _rank_athletics > 0,
		prof_acrobatics = _rank_acrobatics > 0,
		prof_sleight_of_hand = _rank_sleight_of_hand > 0,
		prof_stealth = _rank_stealth > 0,
		prof_arcana = _rank_arcana > 0,
		prof_history = _rank_history > 0,
		prof_investigation = _rank_investigation > 0,
		prof_nature = _rank_nature > 0,
		prof_religion = _rank_religion > 0,
		prof_animal_handling = _rank_animal_handling > 0,
		prof_insight = _rank_insight > 0,
		prof_medicine = _rank_medicine > 0,
		prof_perception = _rank_perception > 0,
		prof_survival = _rank_survival > 0,
		prof_deception = _rank_deception > 0,
		prof_intimidation = _rank_intimidation > 0,
		prof_performance = _rank_performance > 0,
		prof_persuasion = _rank_persuasion > 0,
		save_str = _save_str,
		save_dex = _save_dex,
		save_con = _save_con,
		save_int = _save_int,
		save_wis = _save_wis,
		save_cha = _save_cha,
		ability = _ability,
		abilities = _abilities,
		notes = _notes,
		tera_type = _tera_type,
		exp = _exp,
		status = _status,
		held_item = _held_item,
		is_shiny = _is_shiny,
		custom_size = _custom_size,
		hit_dice_size = _hit_dice_size,
		speed_walking = _speed_walking,
		speed_climbing = _speed_climbing,
		speed_swimming = _speed_swimming,
		speed_flying = _speed_flying,
		speed_hover = _speed_hover,
		speed_burrowing = _speed_burrowing,
		sense_darkvision = _sense_darkvision,
		sense_blindsight = _sense_blindsight,
		sense_tremorsense = _sense_tremorsense,
		sense_truesight = _sense_truesight,
		bond_level = _bond_level,
		bond_points_cur = _bond_points_cur,
		bond_points_max = _bond_points_max,
		rank_athletics = _rank_athletics,
		rank_acrobatics = _rank_acrobatics,
		rank_sleight_of_hand = _rank_sleight_of_hand,
		rank_stealth = _rank_stealth,
		rank_arcana = _rank_arcana,
		rank_history = _rank_history,
		rank_investigation = _rank_investigation,
		rank_nature = _rank_nature,
		rank_religion = _rank_religion,
		rank_animal_handling = _rank_animal_handling,
		rank_insight = _rank_insight,
		rank_medicine = _rank_medicine,
		rank_perception = _rank_perception,
		rank_survival = _rank_survival,
		rank_deception = _rank_deception,
		rank_intimidation = _rank_intimidation,
		rank_performance = _rank_performance,
		rank_persuasion = _rank_persuasion,
		stab_base = _stab_base,
		stab_bonus = _stab_bonus,
		tags = _tags
	FROM private.trainers t
	WHERE
		p.id = _id
		AND trainer_id = t.id
		AND t.write_key = _write_key;
		
	GET DIAGNOSTICS affected_rows := ROW_COUNT;

	RETURN affected_rows;
END $$ LANGUAGE PLPGSQL VOLATILE SECURITY DEFINER;

---------------------------------------------

ALTER TABLE private.fakemon
	ADD COLUMN biomes VARCHAR(255)[] DEFAULT '{}',
	ADD COLUMN tags VARCHAR(255)[] DEFAULT '{}';

DROP FUNCTION get_fakemon;

CREATE OR REPLACE FUNCTION get_fakemon(_read_key VARCHAR(32))
RETURNS TABLE (
	id UUID,
	read_key VARCHAR(32),
	species_name VARCHAR(255),
	type VARCHAR(255)[],
	size VARCHAR(255),
	sr VARCHAR(255),
	min_level INT,
	egg_groups VARCHAR(255)[],
	gender VARCHAR(255),
	description TEXT,
	ac INT,
	hp INT,
	hit_dice VARCHAR(4),
	speed_walking INT,
	speed_climbing INT,
	speed_swimming INT,
	speed_flying INT,
	speed_hover INT,
	speed_burrowing INT,
	sense_darkvision INT,
	sense_blindsight INT,
	sense_tremorsense INT,
	sense_truesight INT,
	strength INT,
	dexterity INT,
	constitution INT,
	intelligence INT,
	wisdom INT,
	charisma INT,
	prof_athletics BOOLEAN,
	prof_acrobatics BOOLEAN,
	prof_sleight_of_hand BOOLEAN,
	prof_stealth BOOLEAN,
	prof_arcana BOOLEAN,
	prof_history BOOLEAN,
	prof_investigation BOOLEAN,
	prof_nature BOOLEAN,
	prof_religion BOOLEAN,
	prof_animal_handling BOOLEAN,
	prof_insight BOOLEAN,
	prof_medicine BOOLEAN,
	prof_perception BOOLEAN,
	prof_survival BOOLEAN,
	prof_deception BOOLEAN,
	prof_intimidation BOOLEAN,
	prof_performance BOOLEAN,
	prof_persuasion BOOLEAN,
	save_str BOOLEAN,
	save_dex BOOLEAN,
	save_con BOOLEAN,
	save_int BOOLEAN,
	save_wis BOOLEAN,
	save_cha BOOLEAN,
	abilities VARCHAR(255)[],
	hidden_abilities VARCHAR(255)[],
	ability_pool JSON,
	moves_start VARCHAR(255)[],
	moves_level2 VARCHAR(255)[],
	moves_level6 VARCHAR(255)[],
	moves_level10 VARCHAR(255)[],
	moves_level14 VARCHAR(255)[],
	moves_level18 VARCHAR(255)[],
	moves_egg VARCHAR(255)[],
	moves_tm INT[],
	normal_portrait_filename VARCHAR(255),
	normal_sprite_filename VARCHAR(255),
	shiny_portrait_filename VARCHAR(255),
	shiny_sprite_filename VARCHAR(255),
	art_attribution_name VARCHAR(255),
	art_attribution_href VARCHAR(255),
	shiny_hue_rotation INT,
	art_attribution_type VARCHAR(255),
	sprite_attribution_type VARCHAR(255),
	sprite_attribution_name VARCHAR(255),
	sprite_attribution_href VARCHAR(255),
	notes TEXT,
	biomes VARCHAR(255)[],
	tags VARCHAR(255)[]
) AS $$
BEGIN
	RETURN QUERY SELECT
		fakemon.id,
		fakemon.read_key,
		fakemon.species_name,
		fakemon.type,
		fakemon.size,
		fakemon.sr,
		fakemon.min_level,
		fakemon.egg_groups,
		fakemon.gender,
		fakemon.description,
		fakemon.ac,
		fakemon.hp,
		fakemon.hit_dice,
		fakemon.speed_walking,
		fakemon.speed_climbing,
		fakemon.speed_swimming,
		fakemon.speed_flying,
		fakemon.speed_hover,
		fakemon.speed_burrowing,
		fakemon.sense_darkvision,
		fakemon.sense_blindsight,
		fakemon.sense_tremorsense,
		fakemon.sense_truesight,
		fakemon.strength,
		fakemon.dexterity,
		fakemon.constitution,
		fakemon.intelligence,
		fakemon.wisdom,
		fakemon.charisma,
		fakemon.prof_athletics,
		fakemon.prof_acrobatics,
		fakemon.prof_sleight_of_hand,
		fakemon.prof_stealth,
		fakemon.prof_arcana,
		fakemon.prof_history,
		fakemon.prof_investigation,
		fakemon.prof_nature,
		fakemon.prof_religion,
		fakemon.prof_animal_handling,
		fakemon.prof_insight,
		fakemon.prof_medicine,
		fakemon.prof_perception,
		fakemon.prof_survival,
		fakemon.prof_deception,
		fakemon.prof_intimidation,
		fakemon.prof_performance,
		fakemon.prof_persuasion,
		fakemon.save_str,
		fakemon.save_dex,
		fakemon.save_con,
		fakemon.save_int,
		fakemon.save_wis,
		fakemon.save_cha,
		fakemon.abilities,
		fakemon.hidden_abilities,
		fakemon.ability_pool,
		fakemon.moves_start,
		fakemon.moves_level2,
		fakemon.moves_level6,
		fakemon.moves_level10,
		fakemon.moves_level14,
		fakemon.moves_level18,
		fakemon.moves_egg,
		fakemon.moves_tm,
		fakemon.normal_portrait_filename,
		fakemon.normal_sprite_filename,
		fakemon.shiny_portrait_filename,
		fakemon.shiny_sprite_filename,
		fakemon.art_attribution_name,
		fakemon.art_attribution_href,
		fakemon.shiny_hue_rotation,
		fakemon.art_attribution_type,
		fakemon.sprite_attribution_type,
		fakemon.sprite_attribution_name,
		fakemon.sprite_attribution_href,
		fakemon.notes,
		fakemon.biomes,
		fakemon.tags
	FROM private.fakemon WHERE fakemon.read_key = _read_key;
END $$ LANGUAGE PLPGSQL STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION new_fakemon(
	_species_name VARCHAR(255),
	_type VARCHAR(255)[],
	_size VARCHAR(255),
	_sr VARCHAR(255),
	_min_level INT,
	_egg_groups VARCHAR(255)[],
	_gender VARCHAR(255),
	_description TEXT,
	_ac INT,
	_hp INT,
	_hit_dice VARCHAR(4),
	_speed_walking INT,
	_speed_climbing INT,
	_speed_swimming INT,
	_speed_flying INT,
	_speed_hover INT,
	_speed_burrowing INT,
	_sense_darkvision INT,
	_sense_blindsight INT,
	_sense_tremorsense INT,
	_sense_truesight INT,
	_strength INT,
	_dexterity INT,
	_constitution INT,
	_intelligence INT,
	_wisdom INT,
	_charisma INT,
	_prof_athletics BOOLEAN,
	_prof_acrobatics BOOLEAN,
	_prof_sleight_of_hand BOOLEAN,
	_prof_stealth BOOLEAN,
	_prof_arcana BOOLEAN,
	_prof_history BOOLEAN,
	_prof_investigation BOOLEAN,
	_prof_nature BOOLEAN,
	_prof_religion BOOLEAN,
	_prof_animal_handling BOOLEAN,
	_prof_insight BOOLEAN,
	_prof_medicine BOOLEAN,
	_prof_perception BOOLEAN,
	_prof_survival BOOLEAN,
	_prof_deception BOOLEAN,
	_prof_intimidation BOOLEAN,
	_prof_performance BOOLEAN,
	_prof_persuasion BOOLEAN,
	_save_str BOOLEAN,
	_save_dex BOOLEAN,
	_save_con BOOLEAN,
	_save_int BOOLEAN,
	_save_wis BOOLEAN,
	_save_cha BOOLEAN,
	_abilities VARCHAR(255)[],
	_hidden_abilities VARCHAR(255)[],
	_ability_pool JSON,
	_moves_start VARCHAR(255)[],
	_moves_level2 VARCHAR(255)[],
	_moves_level6 VARCHAR(255)[],
	_moves_level10 VARCHAR(255)[],
	_moves_level14 VARCHAR(255)[],
	_moves_level18 VARCHAR(255)[],
	_moves_egg VARCHAR(255)[],
	_moves_tm INT[],
	_art_attribution_name VARCHAR(255),
	_art_attribution_href VARCHAR(255),
	_shiny_hue_rotation INT,
	_art_attribution_type VARCHAR(255),
	_sprite_attribution_type VARCHAR(255),
	_sprite_attribution_name VARCHAR(255),
	_sprite_attribution_href VARCHAR(255),
	_notes TEXT,
	_biomes VARCHAR(255)[],
	_tags VARCHAR(255)[],
	OUT ret_id UUID,
	OUT ret_read_key VARCHAR(32),
	OUT ret_write_key VARCHAR(32)
) AS $$
BEGIN
	INSERT INTO private.fakemon (
		species_name,
		type,
		size,
		sr,
		min_level,
		egg_groups,
		gender,
		description,
		ac,
		hp,
		hit_dice,
		speed_walking,
		speed_climbing,
		speed_swimming,
		speed_flying,
		speed_hover,
		speed_burrowing,
		sense_darkvision,
		sense_blindsight,
		sense_tremorsense,
		sense_truesight,
		strength,
		dexterity,
		constitution,
		intelligence,
		wisdom,
		charisma,
		prof_athletics,
		prof_acrobatics,
		prof_sleight_of_hand,
		prof_stealth,
		prof_arcana,
		prof_history,
		prof_investigation,
		prof_nature,
		prof_religion,
		prof_animal_handling,
		prof_insight,
		prof_medicine,
		prof_perception,
		prof_survival,
		prof_deception,
		prof_intimidation,
		prof_performance,
		prof_persuasion,
		save_str,
		save_dex,
		save_con,
		save_int,
		save_wis,
		save_cha,
		abilities,
		hidden_abilities,
		ability_pool,
		moves_start,
		moves_level2,
		moves_level6,
		moves_level10,
		moves_level14,
		moves_level18,
		moves_egg,
		moves_tm,
		art_attribution_name,
		art_attribution_href,
		shiny_hue_rotation,
		art_attribution_type,
		sprite_attribution_type,
		sprite_attribution_name,
		sprite_attribution_href,
		notes,
		biomes,
		tags
	) VALUES (
		_species_name,
		_type,
		_size,
		_sr,
		_min_level,
		_egg_groups,
		_gender,
		_description,
		_ac,
		_hp,
		_hit_dice,
		_speed_walking,
		_speed_climbing,
		_speed_swimming,
		_speed_flying,
		_speed_hover,
		_speed_burrowing,
		_sense_darkvision,
		_sense_blindsight,
		_sense_tremorsense,
		_sense_truesight,
		_strength,
		_dexterity,
		_constitution,
		_intelligence,
		_wisdom,
		_charisma,
		_prof_athletics,
		_prof_acrobatics,
		_prof_sleight_of_hand,
		_prof_stealth,
		_prof_arcana,
		_prof_history,
		_prof_investigation,
		_prof_nature,
		_prof_religion,
		_prof_animal_handling,
		_prof_insight,
		_prof_medicine,
		_prof_perception,
		_prof_survival,
		_prof_deception,
		_prof_intimidation,
		_prof_performance,
		_prof_persuasion,
		_save_str,
		_save_dex,
		_save_con,
		_save_int,
		_save_wis,
		_save_cha,
		_abilities,
		_hidden_abilities,
		_ability_pool,
		_moves_start,
		_moves_level2,
		_moves_level6,
		_moves_level10,
		_moves_level14,
		_moves_level18,
		_moves_egg,
		_moves_tm,
		_art_attribution_name,
		_art_attribution_href,
		_shiny_hue_rotation,
		_art_attribution_type,
		_sprite_attribution_type,
		_sprite_attribution_name,
		_sprite_attribution_href,
		_notes,
		_biomes,
		_tags
	) RETURNING id, read_key, write_key INTO ret_id, ret_read_key, ret_write_key;
END $$ LANGUAGE PLPGSQL VOLATILE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION update_fakemon(
	_write_key VARCHAR(32),
	_species_name VARCHAR(255),
	_type VARCHAR(255)[],
	_size VARCHAR(255),
	_sr VARCHAR(255),
	_min_level INT,
	_egg_groups VARCHAR(255)[],
	_gender VARCHAR(255),
	_description TEXT,
	_ac INT,
	_hp INT,
	_hit_dice VARCHAR(4),
	_speed_walking INT,
	_speed_climbing INT,
	_speed_swimming INT,
	_speed_flying INT,
	_speed_hover INT,
	_speed_burrowing INT,
	_sense_darkvision INT,
	_sense_blindsight INT,
	_sense_tremorsense INT,
	_sense_truesight INT,
	_strength INT,
	_dexterity INT,
	_constitution INT,
	_intelligence INT,
	_wisdom INT,
	_charisma INT,
	_prof_athletics BOOLEAN,
	_prof_acrobatics BOOLEAN,
	_prof_sleight_of_hand BOOLEAN,
	_prof_stealth BOOLEAN,
	_prof_arcana BOOLEAN,
	_prof_history BOOLEAN,
	_prof_investigation BOOLEAN,
	_prof_nature BOOLEAN,
	_prof_religion BOOLEAN,
	_prof_animal_handling BOOLEAN,
	_prof_insight BOOLEAN,
	_prof_medicine BOOLEAN,
	_prof_perception BOOLEAN,
	_prof_survival BOOLEAN,
	_prof_deception BOOLEAN,
	_prof_intimidation BOOLEAN,
	_prof_performance BOOLEAN,
	_prof_persuasion BOOLEAN,
	_save_str BOOLEAN,
	_save_dex BOOLEAN,
	_save_con BOOLEAN,
	_save_int BOOLEAN,
	_save_wis BOOLEAN,
	_save_cha BOOLEAN,
	_abilities VARCHAR(255)[],
	_hidden_abilities VARCHAR(255)[],
	_ability_pool JSON,
	_moves_start VARCHAR(255)[],
	_moves_level2 VARCHAR(255)[],
	_moves_level6 VARCHAR(255)[],
	_moves_level10 VARCHAR(255)[],
	_moves_level14 VARCHAR(255)[],
	_moves_level18 VARCHAR(255)[],
	_moves_egg VARCHAR(255)[],
	_moves_tm INT[],
	_art_attribution_name VARCHAR(255),
	_art_attribution_href VARCHAR(255),
	_shiny_hue_rotation INT,
	_art_attribution_type VARCHAR(255),
	_sprite_attribution_type VARCHAR(255),
	_sprite_attribution_name VARCHAR(255),
	_sprite_attribution_href VARCHAR(255),
	_notes TEXT,
	_biomes VARCHAR(255)[],
	_tags VARCHAR(255)[]
) RETURNS INT AS $$
DECLARE affected_rows INT;
BEGIN
	UPDATE private.fakemon SET
		species_name = _species_name,
		type = _type,
		size = _size,
		sr = _sr,
		min_level = _min_level,
		egg_groups = _egg_groups,
		gender = _gender,
		description = _description,
		ac = _ac,
		hp = _hp,
		hit_dice = _hit_dice,
		speed_walking = _speed_walking,
		speed_climbing = _speed_climbing,
		speed_swimming = _speed_swimming,
		speed_flying = _speed_flying,
		speed_hover = _speed_hover,
		speed_burrowing = _speed_burrowing,
		sense_darkvision = _sense_darkvision,
		sense_blindsight = _sense_blindsight,
		sense_tremorsense = _sense_tremorsense,
		sense_truesight = _sense_truesight,
		strength = _strength,
		dexterity = _dexterity,
		constitution = _constitution,
		intelligence = _intelligence,
		wisdom = _wisdom,
		charisma = _charisma,
		prof_athletics = _prof_athletics,
		prof_acrobatics = _prof_acrobatics,
		prof_sleight_of_hand = _prof_sleight_of_hand,
		prof_stealth = _prof_stealth,
		prof_arcana = _prof_arcana,
		prof_history = _prof_history,
		prof_investigation = _prof_investigation,
		prof_nature = _prof_nature,
		prof_religion = _prof_religion,
		prof_animal_handling = _prof_animal_handling,
		prof_insight = _prof_insight,
		prof_medicine = _prof_medicine,
		prof_perception = _prof_perception,
		prof_survival = _prof_survival,
		prof_deception = _prof_deception,
		prof_intimidation = _prof_intimidation,
		prof_performance = _prof_performance,
		prof_persuasion = _prof_persuasion,
		save_str = _save_str,
		save_dex = _save_dex,
		save_con = _save_con,
		save_int = _save_int,
		save_wis = _save_wis,
		save_cha = _save_cha,
		abilities = _abilities,
		hidden_abilities = _hidden_abilities,
		ability_pool = _ability_pool,
		moves_start = _moves_start,
		moves_level2 = _moves_level2,
		moves_level6 = _moves_level6,
		moves_level10 = _moves_level10,
		moves_level14 = _moves_level14,
		moves_level18 = _moves_level18,
		moves_egg = _moves_egg,
		moves_tm = _moves_tm,
		art_attribution_name = _art_attribution_name,
		art_attribution_href = _art_attribution_href,
		shiny_hue_rotation = _shiny_hue_rotation,
		art_attribution_type = _art_attribution_type,
		sprite_attribution_type = _sprite_attribution_type,
		sprite_attribution_name = _sprite_attribution_name,
		sprite_attribution_href = _sprite_attribution_href,
		notes = _notes,
		biomes = _biomes,
		tags = _tags
	WHERE
		write_key = _write_key;
	
	GET DIAGNOSTICS affected_rows := ROW_COUNT;

	RETURN affected_rows;
END $$ LANGUAGE PLPGSQL VOLATILE SECURITY DEFINER;
