name: Frontend Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/routes/version-history/versions.ts

jobs:
  unit-tests:
    uses: ./.github/workflows/test.yml

  site-deploy:
    name: Site Deploy
    needs: unit-tests
    runs-on: ubuntu-latest
    env:
      PUBLIC_ANALYTICS_ENABLED: true
      PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
      PUBLIC_SUPABASE_KEY: ${{ secrets.PUBLIC_SUPABASE_KEY }}
      PUBLIC_USER_ASSETS_BASE_URL: ${{ secrets.PUBLIC_USER_ASSETS_BASE_URL }}
      ENV: prod
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: poke5e.app

  smoke-test:
    needs: site-deploy
    uses: ./.github/workflows/smoke.yml
