name: Unit Tests
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - src/**
      - static/**

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      PUBLIC_OFFLINE: false
      PUBLIC_ANALYTICS_ENABLED: false
      PUBLIC_SUPABASE_URL: http://127.0.0.1:54321
      PUBLIC_SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      PUBLIC_USER_ASSETS_BASE_URL: http://127.0.0.1:9000/user-assets
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: pnpm install --frozen-lockfile
      - run: pnpm exec playwright install
      - run: pnpm services:start
      - run: pnpm supabase db reset
      - name: Unit Test
        run: pnpm test:unit
